// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sharing

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewDeletionOwnershipErrorMock creates a new instance of DeletionOwnershipErrorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeletionOwnershipErrorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeletionOwnershipErrorMock {
	mock := &DeletionOwnershipErrorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeletionOwnershipErrorMock is an autogenerated mock type for the DeletionOwnershipError type
type DeletionOwnershipErrorMock struct {
	mock.Mock
}

type DeletionOwnershipErrorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DeletionOwnershipErrorMock) EXPECT() *DeletionOwnershipErrorMock_Expecter {
	return &DeletionOwnershipErrorMock_Expecter{mock: &_m.Mock}
}

// ErrorResourceDeletionRestrictedToOwner provides a mock function for the type DeletionOwnershipErrorMock
func (_mock *DeletionOwnershipErrorMock) ErrorResourceDeletionRestrictedToOwner() *common.ServiceError {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorResourceDeletionRestrictedToOwner")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func() *common.ServiceError); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorResourceDeletionRestrictedToOwner'
type DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call struct {
	*mock.Call
}

// ErrorResourceDeletionRestrictedToOwner is a helper method to define mock.On call
func (_e *DeletionOwnershipErrorMock_Expecter) ErrorResourceDeletionRestrictedToOwner() *DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call {
	return &DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call{Call: _e.mock.On("ErrorResourceDeletionRestrictedToOwner")}
}

func (_c *DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call) Run(run func()) *DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call) Return(serviceError *common.ServiceError) *DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call) RunAndReturn(run func() *common.ServiceError) *DeletionOwnershipErrorMock_ErrorResourceDeletionRestrictedToOwner_Call {
	_c.Call.Return(run)
	return _c
}
