// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sharing

import (
	mock "github.com/stretchr/testify/mock"
)

// NewResourceTypeDeclarationMock creates a new instance of ResourceTypeDeclarationMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceTypeDeclarationMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceTypeDeclarationMock {
	mock := &ResourceTypeDeclarationMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceTypeDeclarationMock is an autogenerated mock type for the ResourceTypeDeclaration type
type ResourceTypeDeclarationMock struct {
	mock.Mock
}

type ResourceTypeDeclarationMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceTypeDeclarationMock) EXPECT() *ResourceTypeDeclarationMock_Expecter {
	return &ResourceTypeDeclarationMock_Expecter{mock: &_m.Mock}
}

// ResourceType provides a mock function for the type ResourceTypeDeclarationMock
func (_mock *ResourceTypeDeclarationMock) ResourceType() ResourceType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResourceType")
	}

	var r0 ResourceType
	if returnFunc, ok := ret.Get(0).(func() ResourceType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ResourceType)
	}
	return r0
}

// ResourceTypeDeclarationMock_ResourceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceType'
type ResourceTypeDeclarationMock_ResourceType_Call struct {
	*mock.Call
}

// ResourceType is a helper method to define mock.On call
func (_e *ResourceTypeDeclarationMock_Expecter) ResourceType() *ResourceTypeDeclarationMock_ResourceType_Call {
	return &ResourceTypeDeclarationMock_ResourceType_Call{Call: _e.mock.On("ResourceType")}
}

func (_c *ResourceTypeDeclarationMock_ResourceType_Call) Run(run func()) *ResourceTypeDeclarationMock_ResourceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ResourceTypeDeclarationMock_ResourceType_Call) Return(resourceType ResourceType) *ResourceTypeDeclarationMock_ResourceType_Call {
	_c.Call.Return(resourceType)
	return _c
}

func (_c *ResourceTypeDeclarationMock_ResourceType_Call) RunAndReturn(run func() ResourceType) *ResourceTypeDeclarationMock_ResourceType_Call {
	_c.Call.Return(run)
	return _c
}

// TemplatedFields provides a mock function for the type ResourceTypeDeclarationMock
func (_mock *ResourceTypeDeclarationMock) TemplatedFields() []TemplatedFieldDeclaration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TemplatedFields")
	}

	var r0 []TemplatedFieldDeclaration
	if returnFunc, ok := ret.Get(0).(func() []TemplatedFieldDeclaration); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TemplatedFieldDeclaration)
		}
	}
	return r0
}

// ResourceTypeDeclarationMock_TemplatedFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TemplatedFields'
type ResourceTypeDeclarationMock_TemplatedFields_Call struct {
	*mock.Call
}

// TemplatedFields is a helper method to define mock.On call
func (_e *ResourceTypeDeclarationMock_Expecter) TemplatedFields() *ResourceTypeDeclarationMock_TemplatedFields_Call {
	return &ResourceTypeDeclarationMock_TemplatedFields_Call{Call: _e.mock.On("TemplatedFields")}
}

func (_c *ResourceTypeDeclarationMock_TemplatedFields_Call) Run(run func()) *ResourceTypeDeclarationMock_TemplatedFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ResourceTypeDeclarationMock_TemplatedFields_Call) Return(templatedFieldDeclarations []TemplatedFieldDeclaration) *ResourceTypeDeclarationMock_TemplatedFields_Call {
	_c.Call.Return(templatedFieldDeclarations)
	return _c
}

func (_c *ResourceTypeDeclarationMock_TemplatedFields_Call) RunAndReturn(run func() []TemplatedFieldDeclaration) *ResourceTypeDeclarationMock_TemplatedFields_Call {
	_c.Call.Return(run)
	return _c
}
