// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sharing

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewServiceInterfaceMock creates a new instance of ServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceInterfaceMock {
	mock := &ServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceInterfaceMock is an autogenerated mock type for the ServiceInterface type
type ServiceInterfaceMock struct {
	mock.Mock
}

type ServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceInterfaceMock) EXPECT() *ServiceInterfaceMock_Expecter {
	return &ServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// ExportGrants provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) ExportGrants(ctx context.Context, resourceType ResourceType, resourceID string) ([]ReplayableGrant, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for ExportGrants")
	}

	var r0 []ReplayableGrant
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) ([]ReplayableGrant, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) []ReplayableGrant); ok {
		r0 = returnFunc(ctx, resourceType, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ReplayableGrant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, resourceID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_ExportGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportGrants'
type ServiceInterfaceMock_ExportGrants_Call struct {
	*mock.Call
}

// ExportGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
func (_e *ServiceInterfaceMock_Expecter) ExportGrants(ctx interface{}, resourceType interface{}, resourceID interface{}) *ServiceInterfaceMock_ExportGrants_Call {
	return &ServiceInterfaceMock_ExportGrants_Call{Call: _e.mock.On("ExportGrants", ctx, resourceType, resourceID)}
}

func (_c *ServiceInterfaceMock_ExportGrants_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string)) *ServiceInterfaceMock_ExportGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_ExportGrants_Call) Return(replayableGrants []ReplayableGrant, serviceError *common.ServiceError) *ServiceInterfaceMock_ExportGrants_Call {
	_c.Call.Return(replayableGrants, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_ExportGrants_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string) ([]ReplayableGrant, *common.ServiceError)) *ServiceInterfaceMock_ExportGrants_Call {
	_c.Call.Return(run)
	return _c
}

// IsShared provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) IsShared(ctx context.Context, resourceType ResourceType, resourceID string, ouID string) (bool, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, resourceID, ouID)

	if len(ret) == 0 {
		panic("no return value specified for IsShared")
	}

	var r0 bool
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string) (bool, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, resourceID, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string) bool); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, ouID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, ouID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_IsShared_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsShared'
type ServiceInterfaceMock_IsShared_Call struct {
	*mock.Call
}

// IsShared is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - ouID string
func (_e *ServiceInterfaceMock_Expecter) IsShared(ctx interface{}, resourceType interface{}, resourceID interface{}, ouID interface{}) *ServiceInterfaceMock_IsShared_Call {
	return &ServiceInterfaceMock_IsShared_Call{Call: _e.mock.On("IsShared", ctx, resourceType, resourceID, ouID)}
}

func (_c *ServiceInterfaceMock_IsShared_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, ouID string)) *ServiceInterfaceMock_IsShared_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_IsShared_Call) Return(b bool, serviceError *common.ServiceError) *ServiceInterfaceMock_IsShared_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_IsShared_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, ouID string) (bool, *common.ServiceError)) *ServiceInterfaceMock_IsShared_Call {
	_c.Call.Return(run)
	return _c
}

// ListGrants provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) ListGrants(ctx context.Context, resourceType ResourceType, resourceID string) ([]Grant, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for ListGrants")
	}

	var r0 []Grant
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) ([]Grant, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) []Grant); ok {
		r0 = returnFunc(ctx, resourceType, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, resourceID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_ListGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGrants'
type ServiceInterfaceMock_ListGrants_Call struct {
	*mock.Call
}

// ListGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
func (_e *ServiceInterfaceMock_Expecter) ListGrants(ctx interface{}, resourceType interface{}, resourceID interface{}) *ServiceInterfaceMock_ListGrants_Call {
	return &ServiceInterfaceMock_ListGrants_Call{Call: _e.mock.On("ListGrants", ctx, resourceType, resourceID)}
}

func (_c *ServiceInterfaceMock_ListGrants_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string)) *ServiceInterfaceMock_ListGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_ListGrants_Call) Return(grants []Grant, serviceError *common.ServiceError) *ServiceInterfaceMock_ListGrants_Call {
	_c.Call.Return(grants, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_ListGrants_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string) ([]Grant, *common.ServiceError)) *ServiceInterfaceMock_ListGrants_Call {
	_c.Call.Return(run)
	return _c
}

// ListGrantsPage provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) ListGrantsPage(ctx context.Context, resourceType ResourceType, resourceID string, limit int, offset int) (*GrantPage, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, resourceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListGrantsPage")
	}

	var r0 *GrantPage
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, int, int) (*GrantPage, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, resourceID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, int, int) *GrantPage); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GrantPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string, int, int) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_ListGrantsPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGrantsPage'
type ServiceInterfaceMock_ListGrantsPage_Call struct {
	*mock.Call
}

// ListGrantsPage is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - limit int
//   - offset int
func (_e *ServiceInterfaceMock_Expecter) ListGrantsPage(ctx interface{}, resourceType interface{}, resourceID interface{}, limit interface{}, offset interface{}) *ServiceInterfaceMock_ListGrantsPage_Call {
	return &ServiceInterfaceMock_ListGrantsPage_Call{Call: _e.mock.On("ListGrantsPage", ctx, resourceType, resourceID, limit, offset)}
}

func (_c *ServiceInterfaceMock_ListGrantsPage_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, limit int, offset int)) *ServiceInterfaceMock_ListGrantsPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_ListGrantsPage_Call) Return(grantPage *GrantPage, serviceError *common.ServiceError) *ServiceInterfaceMock_ListGrantsPage_Call {
	_c.Call.Return(grantPage, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_ListGrantsPage_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, limit int, offset int) (*GrantPage, *common.ServiceError)) *ServiceInterfaceMock_ListGrantsPage_Call {
	_c.Call.Return(run)
	return _c
}

// ListSharedResourceIDs provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) ListSharedResourceIDs(ctx context.Context, resourceType ResourceType, ouID string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, ouID)

	if len(ret) == 0 {
		panic("no return value specified for ListSharedResourceIDs")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) []string); ok {
		r0 = returnFunc(ctx, resourceType, ouID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, ouID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_ListSharedResourceIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSharedResourceIDs'
type ServiceInterfaceMock_ListSharedResourceIDs_Call struct {
	*mock.Call
}

// ListSharedResourceIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - ouID string
func (_e *ServiceInterfaceMock_Expecter) ListSharedResourceIDs(ctx interface{}, resourceType interface{}, ouID interface{}) *ServiceInterfaceMock_ListSharedResourceIDs_Call {
	return &ServiceInterfaceMock_ListSharedResourceIDs_Call{Call: _e.mock.On("ListSharedResourceIDs", ctx, resourceType, ouID)}
}

func (_c *ServiceInterfaceMock_ListSharedResourceIDs_Call) Run(run func(ctx context.Context, resourceType ResourceType, ouID string)) *ServiceInterfaceMock_ListSharedResourceIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_ListSharedResourceIDs_Call) Return(strings []string, serviceError *common.ServiceError) *ServiceInterfaceMock_ListSharedResourceIDs_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_ListSharedResourceIDs_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, ouID string) ([]string, *common.ServiceError)) *ServiceInterfaceMock_ListSharedResourceIDs_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterResourceType provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) RegisterResourceType(decl ResourceTypeDeclaration) {
	_mock.Called(decl)
	return
}

// ServiceInterfaceMock_RegisterResourceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterResourceType'
type ServiceInterfaceMock_RegisterResourceType_Call struct {
	*mock.Call
}

// RegisterResourceType is a helper method to define mock.On call
//   - decl ResourceTypeDeclaration
func (_e *ServiceInterfaceMock_Expecter) RegisterResourceType(decl interface{}) *ServiceInterfaceMock_RegisterResourceType_Call {
	return &ServiceInterfaceMock_RegisterResourceType_Call{Call: _e.mock.On("RegisterResourceType", decl)}
}

func (_c *ServiceInterfaceMock_RegisterResourceType_Call) Run(run func(decl ResourceTypeDeclaration)) *ServiceInterfaceMock_RegisterResourceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ResourceTypeDeclaration
		if args[0] != nil {
			arg0 = args[0].(ResourceTypeDeclaration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_RegisterResourceType_Call) Return() *ServiceInterfaceMock_RegisterResourceType_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceInterfaceMock_RegisterResourceType_Call) RunAndReturn(run func(decl ResourceTypeDeclaration)) *ServiceInterfaceMock_RegisterResourceType_Call {
	_c.Run(run)
	return _c
}

// RequireOwnership provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) RequireOwnership(ctx context.Context, resourceType ResourceType, owningOUID string) *common.ServiceError {
	ret := _mock.Called(ctx, resourceType, owningOUID)

	if len(ret) == 0 {
		panic("no return value specified for RequireOwnership")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, resourceType, owningOUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ServiceInterfaceMock_RequireOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireOwnership'
type ServiceInterfaceMock_RequireOwnership_Call struct {
	*mock.Call
}

// RequireOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - owningOUID string
func (_e *ServiceInterfaceMock_Expecter) RequireOwnership(ctx interface{}, resourceType interface{}, owningOUID interface{}) *ServiceInterfaceMock_RequireOwnership_Call {
	return &ServiceInterfaceMock_RequireOwnership_Call{Call: _e.mock.On("RequireOwnership", ctx, resourceType, owningOUID)}
}

func (_c *ServiceInterfaceMock_RequireOwnership_Call) Run(run func(ctx context.Context, resourceType ResourceType, owningOUID string)) *ServiceInterfaceMock_RequireOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_RequireOwnership_Call) Return(serviceError *common.ServiceError) *ServiceInterfaceMock_RequireOwnership_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_RequireOwnership_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, owningOUID string) *common.ServiceError) *ServiceInterfaceMock_RequireOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// RequireOwnershipForDeletion provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) RequireOwnershipForDeletion(ctx context.Context, resourceType ResourceType, owningOUID string) *common.ServiceError {
	ret := _mock.Called(ctx, resourceType, owningOUID)

	if len(ret) == 0 {
		panic("no return value specified for RequireOwnershipForDeletion")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, resourceType, owningOUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ServiceInterfaceMock_RequireOwnershipForDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireOwnershipForDeletion'
type ServiceInterfaceMock_RequireOwnershipForDeletion_Call struct {
	*mock.Call
}

// RequireOwnershipForDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - owningOUID string
func (_e *ServiceInterfaceMock_Expecter) RequireOwnershipForDeletion(ctx interface{}, resourceType interface{}, owningOUID interface{}) *ServiceInterfaceMock_RequireOwnershipForDeletion_Call {
	return &ServiceInterfaceMock_RequireOwnershipForDeletion_Call{Call: _e.mock.On("RequireOwnershipForDeletion", ctx, resourceType, owningOUID)}
}

func (_c *ServiceInterfaceMock_RequireOwnershipForDeletion_Call) Run(run func(ctx context.Context, resourceType ResourceType, owningOUID string)) *ServiceInterfaceMock_RequireOwnershipForDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_RequireOwnershipForDeletion_Call) Return(serviceError *common.ServiceError) *ServiceInterfaceMock_RequireOwnershipForDeletion_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_RequireOwnershipForDeletion_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, owningOUID string) *common.ServiceError) *ServiceInterfaceMock_RequireOwnershipForDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveEditability provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) ResolveEditability(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, ouID string, fieldKey string) (bool, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, resourceID, owningOUID, ouID, fieldKey)

	if len(ret) == 0 {
		panic("no return value specified for ResolveEditability")
	}

	var r0 bool
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, string, string) (bool, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, resourceID, owningOUID, ouID, fieldKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, string, string) bool); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, owningOUID, ouID, fieldKey)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string, string, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, owningOUID, ouID, fieldKey)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_ResolveEditability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveEditability'
type ServiceInterfaceMock_ResolveEditability_Call struct {
	*mock.Call
}

// ResolveEditability is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - owningOUID string
//   - ouID string
//   - fieldKey string
func (_e *ServiceInterfaceMock_Expecter) ResolveEditability(ctx interface{}, resourceType interface{}, resourceID interface{}, owningOUID interface{}, ouID interface{}, fieldKey interface{}) *ServiceInterfaceMock_ResolveEditability_Call {
	return &ServiceInterfaceMock_ResolveEditability_Call{Call: _e.mock.On("ResolveEditability", ctx, resourceType, resourceID, owningOUID, ouID, fieldKey)}
}

func (_c *ServiceInterfaceMock_ResolveEditability_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, ouID string, fieldKey string)) *ServiceInterfaceMock_ResolveEditability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_ResolveEditability_Call) Return(b bool, serviceError *common.ServiceError) *ServiceInterfaceMock_ResolveEditability_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_ResolveEditability_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, ouID string, fieldKey string) (bool, *common.ServiceError)) *ServiceInterfaceMock_ResolveEditability_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveEditableFields provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) ResolveEditableFields(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, ouID string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, resourceID, owningOUID, ouID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveEditableFields")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, resourceID, owningOUID, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, string) []string); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, owningOUID, ouID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, owningOUID, ouID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_ResolveEditableFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveEditableFields'
type ServiceInterfaceMock_ResolveEditableFields_Call struct {
	*mock.Call
}

// ResolveEditableFields is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - owningOUID string
//   - ouID string
func (_e *ServiceInterfaceMock_Expecter) ResolveEditableFields(ctx interface{}, resourceType interface{}, resourceID interface{}, owningOUID interface{}, ouID interface{}) *ServiceInterfaceMock_ResolveEditableFields_Call {
	return &ServiceInterfaceMock_ResolveEditableFields_Call{Call: _e.mock.On("ResolveEditableFields", ctx, resourceType, resourceID, owningOUID, ouID)}
}

func (_c *ServiceInterfaceMock_ResolveEditableFields_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, ouID string)) *ServiceInterfaceMock_ResolveEditableFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_ResolveEditableFields_Call) Return(strings []string, serviceError *common.ServiceError) *ServiceInterfaceMock_ResolveEditableFields_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_ResolveEditableFields_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, ouID string) ([]string, *common.ServiceError)) *ServiceInterfaceMock_ResolveEditableFields_Call {
	_c.Call.Return(run)
	return _c
}

// Share provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) Share(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, actingOUID string, policy SharePolicy) ([]Grant, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, resourceID, owningOUID, actingOUID, policy)

	if len(ret) == 0 {
		panic("no return value specified for Share")
	}

	var r0 []Grant
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, string, SharePolicy) ([]Grant, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, resourceID, owningOUID, actingOUID, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, string, SharePolicy) []Grant); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, owningOUID, actingOUID, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string, string, string, SharePolicy) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, owningOUID, actingOUID, policy)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_Share_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Share'
type ServiceInterfaceMock_Share_Call struct {
	*mock.Call
}

// Share is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - owningOUID string
//   - actingOUID string
//   - policy SharePolicy
func (_e *ServiceInterfaceMock_Expecter) Share(ctx interface{}, resourceType interface{}, resourceID interface{}, owningOUID interface{}, actingOUID interface{}, policy interface{}) *ServiceInterfaceMock_Share_Call {
	return &ServiceInterfaceMock_Share_Call{Call: _e.mock.On("Share", ctx, resourceType, resourceID, owningOUID, actingOUID, policy)}
}

func (_c *ServiceInterfaceMock_Share_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, actingOUID string, policy SharePolicy)) *ServiceInterfaceMock_Share_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 SharePolicy
		if args[5] != nil {
			arg5 = args[5].(SharePolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_Share_Call) Return(grants []Grant, serviceError *common.ServiceError) *ServiceInterfaceMock_Share_Call {
	_c.Call.Return(grants, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_Share_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, actingOUID string, policy SharePolicy) ([]Grant, *common.ServiceError)) *ServiceInterfaceMock_Share_Call {
	_c.Call.Return(run)
	return _c
}

// ShareDeclarative provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) ShareDeclarative(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, actingOUID string, policy SharePolicy) ([]Grant, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceType, resourceID, owningOUID, actingOUID, policy)

	if len(ret) == 0 {
		panic("no return value specified for ShareDeclarative")
	}

	var r0 []Grant
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, string, SharePolicy) ([]Grant, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceType, resourceID, owningOUID, actingOUID, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, string, SharePolicy) []Grant); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, owningOUID, actingOUID, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string, string, string, SharePolicy) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, owningOUID, actingOUID, policy)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_ShareDeclarative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareDeclarative'
type ServiceInterfaceMock_ShareDeclarative_Call struct {
	*mock.Call
}

// ShareDeclarative is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - owningOUID string
//   - actingOUID string
//   - policy SharePolicy
func (_e *ServiceInterfaceMock_Expecter) ShareDeclarative(ctx interface{}, resourceType interface{}, resourceID interface{}, owningOUID interface{}, actingOUID interface{}, policy interface{}) *ServiceInterfaceMock_ShareDeclarative_Call {
	return &ServiceInterfaceMock_ShareDeclarative_Call{Call: _e.mock.On("ShareDeclarative", ctx, resourceType, resourceID, owningOUID, actingOUID, policy)}
}

func (_c *ServiceInterfaceMock_ShareDeclarative_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, actingOUID string, policy SharePolicy)) *ServiceInterfaceMock_ShareDeclarative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 SharePolicy
		if args[5] != nil {
			arg5 = args[5].(SharePolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_ShareDeclarative_Call) Return(grants []Grant, serviceError *common.ServiceError) *ServiceInterfaceMock_ShareDeclarative_Call {
	_c.Call.Return(grants, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_ShareDeclarative_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, owningOUID string, actingOUID string, policy SharePolicy) ([]Grant, *common.ServiceError)) *ServiceInterfaceMock_ShareDeclarative_Call {
	_c.Call.Return(run)
	return _c
}

// Unshare provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) Unshare(ctx context.Context, grantID string) *common.ServiceError {
	ret := _mock.Called(ctx, grantID)

	if len(ret) == 0 {
		panic("no return value specified for Unshare")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, grantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ServiceInterfaceMock_Unshare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unshare'
type ServiceInterfaceMock_Unshare_Call struct {
	*mock.Call
}

// Unshare is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
func (_e *ServiceInterfaceMock_Expecter) Unshare(ctx interface{}, grantID interface{}) *ServiceInterfaceMock_Unshare_Call {
	return &ServiceInterfaceMock_Unshare_Call{Call: _e.mock.On("Unshare", ctx, grantID)}
}

func (_c *ServiceInterfaceMock_Unshare_Call) Run(run func(ctx context.Context, grantID string)) *ServiceInterfaceMock_Unshare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_Unshare_Call) Return(serviceError *common.ServiceError) *ServiceInterfaceMock_Unshare_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_Unshare_Call) RunAndReturn(run func(ctx context.Context, grantID string) *common.ServiceError) *ServiceInterfaceMock_Unshare_Call {
	_c.Call.Return(run)
	return _c
}
