// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sharing

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewSharingHooksMock creates a new instance of SharingHooksMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSharingHooksMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SharingHooksMock {
	mock := &SharingHooksMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SharingHooksMock is an autogenerated mock type for the SharingHooks type
type SharingHooksMock struct {
	mock.Mock
}

type SharingHooksMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SharingHooksMock) EXPECT() *SharingHooksMock_Expecter {
	return &SharingHooksMock_Expecter{mock: &_m.Mock}
}

// OnUnshare provides a mock function for the type SharingHooksMock
func (_mock *SharingHooksMock) OnUnshare(ctx context.Context, resourceID string, ouID string) error {
	ret := _mock.Called(ctx, resourceID, ouID)

	if len(ret) == 0 {
		panic("no return value specified for OnUnshare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, resourceID, ouID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SharingHooksMock_OnUnshare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnUnshare'
type SharingHooksMock_OnUnshare_Call struct {
	*mock.Call
}

// OnUnshare is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
//   - ouID string
func (_e *SharingHooksMock_Expecter) OnUnshare(ctx interface{}, resourceID interface{}, ouID interface{}) *SharingHooksMock_OnUnshare_Call {
	return &SharingHooksMock_OnUnshare_Call{Call: _e.mock.On("OnUnshare", ctx, resourceID, ouID)}
}

func (_c *SharingHooksMock_OnUnshare_Call) Run(run func(ctx context.Context, resourceID string, ouID string)) *SharingHooksMock_OnUnshare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SharingHooksMock_OnUnshare_Call) Return(err error) *SharingHooksMock_OnUnshare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SharingHooksMock_OnUnshare_Call) RunAndReturn(run func(ctx context.Context, resourceID string, ouID string) error) *SharingHooksMock_OnUnshare_Call {
	_c.Call.Return(run)
	return _c
}
