// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sharing

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newSharingStoreInterfaceMock creates a new instance of sharingStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSharingStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *sharingStoreInterfaceMock {
	mock := &sharingStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// sharingStoreInterfaceMock is an autogenerated mock type for the sharingStoreInterface type
type sharingStoreInterfaceMock struct {
	mock.Mock
}

type sharingStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *sharingStoreInterfaceMock) EXPECT() *sharingStoreInterfaceMock_Expecter {
	return &sharingStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CountGrantsForResource provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) CountGrantsForResource(ctx context.Context, resourceType ResourceType, resourceID string) (int, error) {
	ret := _mock.Called(ctx, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for CountGrantsForResource")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) (int, error)); ok {
		return returnFunc(ctx, resourceType, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) int); ok {
		r0 = returnFunc(ctx, resourceType, resourceID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string) error); ok {
		r1 = returnFunc(ctx, resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// sharingStoreInterfaceMock_CountGrantsForResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountGrantsForResource'
type sharingStoreInterfaceMock_CountGrantsForResource_Call struct {
	*mock.Call
}

// CountGrantsForResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
func (_e *sharingStoreInterfaceMock_Expecter) CountGrantsForResource(ctx interface{}, resourceType interface{}, resourceID interface{}) *sharingStoreInterfaceMock_CountGrantsForResource_Call {
	return &sharingStoreInterfaceMock_CountGrantsForResource_Call{Call: _e.mock.On("CountGrantsForResource", ctx, resourceType, resourceID)}
}

func (_c *sharingStoreInterfaceMock_CountGrantsForResource_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string)) *sharingStoreInterfaceMock_CountGrantsForResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_CountGrantsForResource_Call) Return(n int, err error) *sharingStoreInterfaceMock_CountGrantsForResource_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *sharingStoreInterfaceMock_CountGrantsForResource_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string) (int, error)) *sharingStoreInterfaceMock_CountGrantsForResource_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGrant provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) CreateGrant(ctx context.Context, grant Grant) error {
	ret := _mock.Called(ctx, grant)

	if len(ret) == 0 {
		panic("no return value specified for CreateGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Grant) error); ok {
		r0 = returnFunc(ctx, grant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// sharingStoreInterfaceMock_CreateGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGrant'
type sharingStoreInterfaceMock_CreateGrant_Call struct {
	*mock.Call
}

// CreateGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - grant Grant
func (_e *sharingStoreInterfaceMock_Expecter) CreateGrant(ctx interface{}, grant interface{}) *sharingStoreInterfaceMock_CreateGrant_Call {
	return &sharingStoreInterfaceMock_CreateGrant_Call{Call: _e.mock.On("CreateGrant", ctx, grant)}
}

func (_c *sharingStoreInterfaceMock_CreateGrant_Call) Run(run func(ctx context.Context, grant Grant)) *sharingStoreInterfaceMock_CreateGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Grant
		if args[1] != nil {
			arg1 = args[1].(Grant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_CreateGrant_Call) Return(err error) *sharingStoreInterfaceMock_CreateGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *sharingStoreInterfaceMock_CreateGrant_Call) RunAndReturn(run func(ctx context.Context, grant Grant) error) *sharingStoreInterfaceMock_CreateGrant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGrant provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) DeleteGrant(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// sharingStoreInterfaceMock_DeleteGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGrant'
type sharingStoreInterfaceMock_DeleteGrant_Call struct {
	*mock.Call
}

// DeleteGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *sharingStoreInterfaceMock_Expecter) DeleteGrant(ctx interface{}, id interface{}) *sharingStoreInterfaceMock_DeleteGrant_Call {
	return &sharingStoreInterfaceMock_DeleteGrant_Call{Call: _e.mock.On("DeleteGrant", ctx, id)}
}

func (_c *sharingStoreInterfaceMock_DeleteGrant_Call) Run(run func(ctx context.Context, id string)) *sharingStoreInterfaceMock_DeleteGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_DeleteGrant_Call) Return(err error) *sharingStoreInterfaceMock_DeleteGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *sharingStoreInterfaceMock_DeleteGrant_Call) RunAndReturn(run func(ctx context.Context, id string) error) *sharingStoreInterfaceMock_DeleteGrant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOverlay provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) DeleteOverlay(ctx context.Context, resourceType ResourceType, resourceID string, ouID string) error {
	ret := _mock.Called(ctx, resourceType, resourceID, ouID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOverlay")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string) error); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, ouID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// sharingStoreInterfaceMock_DeleteOverlay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOverlay'
type sharingStoreInterfaceMock_DeleteOverlay_Call struct {
	*mock.Call
}

// DeleteOverlay is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - ouID string
func (_e *sharingStoreInterfaceMock_Expecter) DeleteOverlay(ctx interface{}, resourceType interface{}, resourceID interface{}, ouID interface{}) *sharingStoreInterfaceMock_DeleteOverlay_Call {
	return &sharingStoreInterfaceMock_DeleteOverlay_Call{Call: _e.mock.On("DeleteOverlay", ctx, resourceType, resourceID, ouID)}
}

func (_c *sharingStoreInterfaceMock_DeleteOverlay_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, ouID string)) *sharingStoreInterfaceMock_DeleteOverlay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_DeleteOverlay_Call) Return(err error) *sharingStoreInterfaceMock_DeleteOverlay_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *sharingStoreInterfaceMock_DeleteOverlay_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, ouID string) error) *sharingStoreInterfaceMock_DeleteOverlay_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrant provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) GetGrant(ctx context.Context, id string) (Grant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGrant")
	}

	var r0 Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Grant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Grant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Grant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// sharingStoreInterfaceMock_GetGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrant'
type sharingStoreInterfaceMock_GetGrant_Call struct {
	*mock.Call
}

// GetGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *sharingStoreInterfaceMock_Expecter) GetGrant(ctx interface{}, id interface{}) *sharingStoreInterfaceMock_GetGrant_Call {
	return &sharingStoreInterfaceMock_GetGrant_Call{Call: _e.mock.On("GetGrant", ctx, id)}
}

func (_c *sharingStoreInterfaceMock_GetGrant_Call) Run(run func(ctx context.Context, id string)) *sharingStoreInterfaceMock_GetGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_GetGrant_Call) Return(grant Grant, err error) *sharingStoreInterfaceMock_GetGrant_Call {
	_c.Call.Return(grant, err)
	return _c
}

func (_c *sharingStoreInterfaceMock_GetGrant_Call) RunAndReturn(run func(ctx context.Context, id string) (Grant, error)) *sharingStoreInterfaceMock_GetGrant_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverlay provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) GetOverlay(ctx context.Context, resourceType ResourceType, resourceID string, ouID string) (map[string]string, bool, error) {
	ret := _mock.Called(ctx, resourceType, resourceID, ouID)

	if len(ret) == 0 {
		panic("no return value specified for GetOverlay")
	}

	var r0 map[string]string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string) (map[string]string, bool, error)); ok {
		return returnFunc(ctx, resourceType, resourceID, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string) map[string]string); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, ouID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string, string) bool); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, ouID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ResourceType, string, string) error); ok {
		r2 = returnFunc(ctx, resourceType, resourceID, ouID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// sharingStoreInterfaceMock_GetOverlay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverlay'
type sharingStoreInterfaceMock_GetOverlay_Call struct {
	*mock.Call
}

// GetOverlay is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - ouID string
func (_e *sharingStoreInterfaceMock_Expecter) GetOverlay(ctx interface{}, resourceType interface{}, resourceID interface{}, ouID interface{}) *sharingStoreInterfaceMock_GetOverlay_Call {
	return &sharingStoreInterfaceMock_GetOverlay_Call{Call: _e.mock.On("GetOverlay", ctx, resourceType, resourceID, ouID)}
}

func (_c *sharingStoreInterfaceMock_GetOverlay_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, ouID string)) *sharingStoreInterfaceMock_GetOverlay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_GetOverlay_Call) Return(stringToString map[string]string, b bool, err error) *sharingStoreInterfaceMock_GetOverlay_Call {
	_c.Call.Return(stringToString, b, err)
	return _c
}

func (_c *sharingStoreInterfaceMock_GetOverlay_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, ouID string) (map[string]string, bool, error)) *sharingStoreInterfaceMock_GetOverlay_Call {
	_c.Call.Return(run)
	return _c
}

// ListChildGrants provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) ListChildGrants(ctx context.Context, parentGrantID string) ([]Grant, error) {
	ret := _mock.Called(ctx, parentGrantID)

	if len(ret) == 0 {
		panic("no return value specified for ListChildGrants")
	}

	var r0 []Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]Grant, error)); ok {
		return returnFunc(ctx, parentGrantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []Grant); ok {
		r0 = returnFunc(ctx, parentGrantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, parentGrantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// sharingStoreInterfaceMock_ListChildGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChildGrants'
type sharingStoreInterfaceMock_ListChildGrants_Call struct {
	*mock.Call
}

// ListChildGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - parentGrantID string
func (_e *sharingStoreInterfaceMock_Expecter) ListChildGrants(ctx interface{}, parentGrantID interface{}) *sharingStoreInterfaceMock_ListChildGrants_Call {
	return &sharingStoreInterfaceMock_ListChildGrants_Call{Call: _e.mock.On("ListChildGrants", ctx, parentGrantID)}
}

func (_c *sharingStoreInterfaceMock_ListChildGrants_Call) Run(run func(ctx context.Context, parentGrantID string)) *sharingStoreInterfaceMock_ListChildGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_ListChildGrants_Call) Return(grants []Grant, err error) *sharingStoreInterfaceMock_ListChildGrants_Call {
	_c.Call.Return(grants, err)
	return _c
}

func (_c *sharingStoreInterfaceMock_ListChildGrants_Call) RunAndReturn(run func(ctx context.Context, parentGrantID string) ([]Grant, error)) *sharingStoreInterfaceMock_ListChildGrants_Call {
	_c.Call.Return(run)
	return _c
}

// ListGrantsForResource provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) ListGrantsForResource(ctx context.Context, resourceType ResourceType, resourceID string) ([]Grant, error) {
	ret := _mock.Called(ctx, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for ListGrantsForResource")
	}

	var r0 []Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) ([]Grant, error)); ok {
		return returnFunc(ctx, resourceType, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string) []Grant); ok {
		r0 = returnFunc(ctx, resourceType, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string) error); ok {
		r1 = returnFunc(ctx, resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// sharingStoreInterfaceMock_ListGrantsForResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGrantsForResource'
type sharingStoreInterfaceMock_ListGrantsForResource_Call struct {
	*mock.Call
}

// ListGrantsForResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
func (_e *sharingStoreInterfaceMock_Expecter) ListGrantsForResource(ctx interface{}, resourceType interface{}, resourceID interface{}) *sharingStoreInterfaceMock_ListGrantsForResource_Call {
	return &sharingStoreInterfaceMock_ListGrantsForResource_Call{Call: _e.mock.On("ListGrantsForResource", ctx, resourceType, resourceID)}
}

func (_c *sharingStoreInterfaceMock_ListGrantsForResource_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string)) *sharingStoreInterfaceMock_ListGrantsForResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_ListGrantsForResource_Call) Return(grants []Grant, err error) *sharingStoreInterfaceMock_ListGrantsForResource_Call {
	_c.Call.Return(grants, err)
	return _c
}

func (_c *sharingStoreInterfaceMock_ListGrantsForResource_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string) ([]Grant, error)) *sharingStoreInterfaceMock_ListGrantsForResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListGrantsForResourcePage provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) ListGrantsForResourcePage(ctx context.Context, resourceType ResourceType, resourceID string, limit int, offset int) ([]Grant, error) {
	ret := _mock.Called(ctx, resourceType, resourceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListGrantsForResourcePage")
	}

	var r0 []Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, int, int) ([]Grant, error)); ok {
		return returnFunc(ctx, resourceType, resourceID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, int, int) []Grant); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, string, int, int) error); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// sharingStoreInterfaceMock_ListGrantsForResourcePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGrantsForResourcePage'
type sharingStoreInterfaceMock_ListGrantsForResourcePage_Call struct {
	*mock.Call
}

// ListGrantsForResourcePage is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - limit int
//   - offset int
func (_e *sharingStoreInterfaceMock_Expecter) ListGrantsForResourcePage(ctx interface{}, resourceType interface{}, resourceID interface{}, limit interface{}, offset interface{}) *sharingStoreInterfaceMock_ListGrantsForResourcePage_Call {
	return &sharingStoreInterfaceMock_ListGrantsForResourcePage_Call{Call: _e.mock.On("ListGrantsForResourcePage", ctx, resourceType, resourceID, limit, offset)}
}

func (_c *sharingStoreInterfaceMock_ListGrantsForResourcePage_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, limit int, offset int)) *sharingStoreInterfaceMock_ListGrantsForResourcePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_ListGrantsForResourcePage_Call) Return(grants []Grant, err error) *sharingStoreInterfaceMock_ListGrantsForResourcePage_Call {
	_c.Call.Return(grants, err)
	return _c
}

func (_c *sharingStoreInterfaceMock_ListGrantsForResourcePage_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, limit int, offset int) ([]Grant, error)) *sharingStoreInterfaceMock_ListGrantsForResourcePage_Call {
	_c.Call.Return(run)
	return _c
}

// ListGrantsRelevantToChain provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) ListGrantsRelevantToChain(ctx context.Context, resourceType ResourceType, chainOUIDs []string) ([]Grant, error) {
	ret := _mock.Called(ctx, resourceType, chainOUIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListGrantsRelevantToChain")
	}

	var r0 []Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, []string) ([]Grant, error)); ok {
		return returnFunc(ctx, resourceType, chainOUIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, []string) []Grant); ok {
		r0 = returnFunc(ctx, resourceType, chainOUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ResourceType, []string) error); ok {
		r1 = returnFunc(ctx, resourceType, chainOUIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGrantsRelevantToChain'
type sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call struct {
	*mock.Call
}

// ListGrantsRelevantToChain is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - chainOUIDs []string
func (_e *sharingStoreInterfaceMock_Expecter) ListGrantsRelevantToChain(ctx interface{}, resourceType interface{}, chainOUIDs interface{}) *sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call {
	return &sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call{Call: _e.mock.On("ListGrantsRelevantToChain", ctx, resourceType, chainOUIDs)}
}

func (_c *sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call) Run(run func(ctx context.Context, resourceType ResourceType, chainOUIDs []string)) *sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call) Return(grants []Grant, err error) *sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call {
	_c.Call.Return(grants, err)
	return _c
}

func (_c *sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, chainOUIDs []string) ([]Grant, error)) *sharingStoreInterfaceMock_ListGrantsRelevantToChain_Call {
	_c.Call.Return(run)
	return _c
}

// SetOverlay provides a mock function for the type sharingStoreInterfaceMock
func (_mock *sharingStoreInterfaceMock) SetOverlay(ctx context.Context, resourceType ResourceType, resourceID string, ouID string, fields map[string]string) error {
	ret := _mock.Called(ctx, resourceType, resourceID, ouID, fields)

	if len(ret) == 0 {
		panic("no return value specified for SetOverlay")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ResourceType, string, string, map[string]string) error); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, ouID, fields)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// sharingStoreInterfaceMock_SetOverlay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOverlay'
type sharingStoreInterfaceMock_SetOverlay_Call struct {
	*mock.Call
}

// SetOverlay is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType ResourceType
//   - resourceID string
//   - ouID string
//   - fields map[string]string
func (_e *sharingStoreInterfaceMock_Expecter) SetOverlay(ctx interface{}, resourceType interface{}, resourceID interface{}, ouID interface{}, fields interface{}) *sharingStoreInterfaceMock_SetOverlay_Call {
	return &sharingStoreInterfaceMock_SetOverlay_Call{Call: _e.mock.On("SetOverlay", ctx, resourceType, resourceID, ouID, fields)}
}

func (_c *sharingStoreInterfaceMock_SetOverlay_Call) Run(run func(ctx context.Context, resourceType ResourceType, resourceID string, ouID string, fields map[string]string)) *sharingStoreInterfaceMock_SetOverlay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ResourceType
		if args[1] != nil {
			arg1 = args[1].(ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *sharingStoreInterfaceMock_SetOverlay_Call) Return(err error) *sharingStoreInterfaceMock_SetOverlay_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *sharingStoreInterfaceMock_SetOverlay_Call) RunAndReturn(run func(ctx context.Context, resourceType ResourceType, resourceID string, ouID string, fields map[string]string) error) *sharingStoreInterfaceMock_SetOverlay_Call {
	_c.Call.Return(run)
	return _c
}
