// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actorprovider

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewApplicationOUAccessCheckerMock creates a new instance of ApplicationOUAccessCheckerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplicationOUAccessCheckerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApplicationOUAccessCheckerMock {
	mock := &ApplicationOUAccessCheckerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ApplicationOUAccessCheckerMock is an autogenerated mock type for the ApplicationOUAccessChecker type
type ApplicationOUAccessCheckerMock struct {
	mock.Mock
}

type ApplicationOUAccessCheckerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ApplicationOUAccessCheckerMock) EXPECT() *ApplicationOUAccessCheckerMock_Expecter {
	return &ApplicationOUAccessCheckerMock_Expecter{mock: &_m.Mock}
}

// IsApplicationGrantedToOU provides a mock function for the type ApplicationOUAccessCheckerMock
func (_mock *ApplicationOUAccessCheckerMock) IsApplicationGrantedToOU(ctx context.Context, appID string, ouID string) (bool, *common.ServiceError) {
	ret := _mock.Called(ctx, appID, ouID)

	if len(ret) == 0 {
		panic("no return value specified for IsApplicationGrantedToOU")
	}

	var r0 bool
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, *common.ServiceError)); ok {
		return returnFunc(ctx, appID, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, appID, ouID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, appID, ouID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsApplicationGrantedToOU'
type ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call struct {
	*mock.Call
}

// IsApplicationGrantedToOU is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - ouID string
func (_e *ApplicationOUAccessCheckerMock_Expecter) IsApplicationGrantedToOU(ctx interface{}, appID interface{}, ouID interface{}) *ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call {
	return &ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call{Call: _e.mock.On("IsApplicationGrantedToOU", ctx, appID, ouID)}
}

func (_c *ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call) Run(run func(ctx context.Context, appID string, ouID string)) *ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call) Return(b bool, serviceError *common.ServiceError) *ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call) RunAndReturn(run func(ctx context.Context, appID string, ouID string) (bool, *common.ServiceError)) *ApplicationOUAccessCheckerMock_IsApplicationGrantedToOU_Call {
	_c.Call.Return(run)
	return _c
}
