// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package role

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/system/resourcedependency"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewRoleAssignmentServiceInterfaceMock creates a new instance of RoleAssignmentServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleAssignmentServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleAssignmentServiceInterfaceMock {
	mock := &RoleAssignmentServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleAssignmentServiceInterfaceMock is an autogenerated mock type for the RoleAssignmentServiceInterface type
type RoleAssignmentServiceInterfaceMock struct {
	mock.Mock
}

type RoleAssignmentServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleAssignmentServiceInterfaceMock) EXPECT() *RoleAssignmentServiceInterfaceMock_Expecter {
	return &RoleAssignmentServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// AddAssigneesToRoles provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) AddAssigneesToRoles(ctx context.Context, assignments []RoleAssignment, roleIDs []string) *common.ServiceError {
	ret := _mock.Called(ctx, assignments, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddAssigneesToRoles")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, []RoleAssignment, []string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, assignments, roleIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAssigneesToRoles'
type RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call struct {
	*mock.Call
}

// AddAssigneesToRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - assignments []RoleAssignment
//   - roleIDs []string
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) AddAssigneesToRoles(ctx interface{}, assignments interface{}, roleIDs interface{}) *RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call {
	return &RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call{Call: _e.mock.On("AddAssigneesToRoles", ctx, assignments, roleIDs)}
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call) Run(run func(ctx context.Context, assignments []RoleAssignment, roleIDs []string)) *RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []RoleAssignment
		if args[1] != nil {
			arg1 = args[1].([]RoleAssignment)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call) Return(serviceError *common.ServiceError) *RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call) RunAndReturn(run func(ctx context.Context, assignments []RoleAssignment, roleIDs []string) *common.ServiceError) *RoleAssignmentServiceInterfaceMock_AddAssigneesToRoles_Call {
	_c.Call.Return(run)
	return _c
}

// AddAssignments provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) AddAssignments(ctx context.Context, id string, ouID string, assignments []RoleAssignment) *common.ServiceError {
	ret := _mock.Called(ctx, id, ouID, assignments)

	if len(ret) == 0 {
		panic("no return value specified for AddAssignments")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []RoleAssignment) *common.ServiceError); ok {
		r0 = returnFunc(ctx, id, ouID, assignments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// RoleAssignmentServiceInterfaceMock_AddAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAssignments'
type RoleAssignmentServiceInterfaceMock_AddAssignments_Call struct {
	*mock.Call
}

// AddAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ouID string
//   - assignments []RoleAssignment
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) AddAssignments(ctx interface{}, id interface{}, ouID interface{}, assignments interface{}) *RoleAssignmentServiceInterfaceMock_AddAssignments_Call {
	return &RoleAssignmentServiceInterfaceMock_AddAssignments_Call{Call: _e.mock.On("AddAssignments", ctx, id, ouID, assignments)}
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssignments_Call) Run(run func(ctx context.Context, id string, ouID string, assignments []RoleAssignment)) *RoleAssignmentServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []RoleAssignment
		if args[3] != nil {
			arg3 = args[3].([]RoleAssignment)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssignments_Call) Return(serviceError *common.ServiceError) *RoleAssignmentServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_AddAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, ouID string, assignments []RoleAssignment) *common.ServiceError) *RoleAssignmentServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// CascadeDeleteDependencies provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) CascadeDeleteDependencies(ctx context.Context, resourceType string, id string) (int, error) {
	ret := _mock.Called(ctx, resourceType, id)

	if len(ret) == 0 {
		panic("no return value specified for CascadeDeleteDependencies")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return returnFunc(ctx, resourceType, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = returnFunc(ctx, resourceType, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceType, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CascadeDeleteDependencies'
type RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call struct {
	*mock.Call
}

// CascadeDeleteDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - id string
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) CascadeDeleteDependencies(ctx interface{}, resourceType interface{}, id interface{}) *RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call {
	return &RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call{Call: _e.mock.On("CascadeDeleteDependencies", ctx, resourceType, id)}
}

func (_c *RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call) Run(run func(ctx context.Context, resourceType string, id string)) *RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call) Return(n int, err error) *RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call) RunAndReturn(run func(ctx context.Context, resourceType string, id string) (int, error)) *RoleAssignmentServiceInterfaceMock_CascadeDeleteDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssigningOUIDs provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) GetAssigningOUIDs(ctx context.Context, id string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAssigningOUIDs")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssigningOUIDs'
type RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call struct {
	*mock.Call
}

// GetAssigningOUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) GetAssigningOUIDs(ctx interface{}, id interface{}) *RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call {
	return &RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call{Call: _e.mock.On("GetAssigningOUIDs", ctx, id)}
}

func (_c *RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call) Run(run func(ctx context.Context, id string)) *RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call) Return(strings []string, serviceError *common.ServiceError) *RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call) RunAndReturn(run func(ctx context.Context, id string) ([]string, *common.ServiceError)) *RoleAssignmentServiceInterfaceMock_GetAssigningOUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetEditableFields provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) GetEditableFields(ctx context.Context, id string, ouID string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, id, ouID)

	if len(ret) == 0 {
		panic("no return value specified for GetEditableFields")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, id, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, id, ouID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id, ouID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_GetEditableFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEditableFields'
type RoleAssignmentServiceInterfaceMock_GetEditableFields_Call struct {
	*mock.Call
}

// GetEditableFields is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ouID string
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) GetEditableFields(ctx interface{}, id interface{}, ouID interface{}) *RoleAssignmentServiceInterfaceMock_GetEditableFields_Call {
	return &RoleAssignmentServiceInterfaceMock_GetEditableFields_Call{Call: _e.mock.On("GetEditableFields", ctx, id, ouID)}
}

func (_c *RoleAssignmentServiceInterfaceMock_GetEditableFields_Call) Run(run func(ctx context.Context, id string, ouID string)) *RoleAssignmentServiceInterfaceMock_GetEditableFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetEditableFields_Call) Return(strings []string, serviceError *common.ServiceError) *RoleAssignmentServiceInterfaceMock_GetEditableFields_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetEditableFields_Call) RunAndReturn(run func(ctx context.Context, id string, ouID string) ([]string, *common.ServiceError)) *RoleAssignmentServiceInterfaceMock_GetEditableFields_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceDependencies provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) GetResourceDependencies(ctx context.Context, resourceType string, id string) ([]resourcedependency.ResourceDependency, error) {
	ret := _mock.Called(ctx, resourceType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceDependencies")
	}

	var r0 []resourcedependency.ResourceDependency
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]resourcedependency.ResourceDependency, error)); ok {
		return returnFunc(ctx, resourceType, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []resourcedependency.ResourceDependency); ok {
		r0 = returnFunc(ctx, resourceType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resourcedependency.ResourceDependency)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceType, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceDependencies'
type RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call struct {
	*mock.Call
}

// GetResourceDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - id string
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) GetResourceDependencies(ctx interface{}, resourceType interface{}, id interface{}) *RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call {
	return &RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call{Call: _e.mock.On("GetResourceDependencies", ctx, resourceType, id)}
}

func (_c *RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call) Run(run func(ctx context.Context, resourceType string, id string)) *RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call) Return(resourceDependencys []resourcedependency.ResourceDependency, err error) *RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Return(resourceDependencys, err)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call) RunAndReturn(run func(ctx context.Context, resourceType string, id string) ([]resourcedependency.ResourceDependency, error)) *RoleAssignmentServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignments provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) GetRoleAssignments(ctx context.Context, id string, ouID string, limit int, offset int, includeDisplay bool) (*AssignmentList, *common.ServiceError) {
	ret := _mock.Called(ctx, id, ouID, limit, offset, includeDisplay)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignments")
	}

	var r0 *AssignmentList
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int, bool) (*AssignmentList, *common.ServiceError)); ok {
		return returnFunc(ctx, id, ouID, limit, offset, includeDisplay)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int, bool) *AssignmentList); ok {
		r0 = returnFunc(ctx, id, ouID, limit, offset, includeDisplay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AssignmentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int, bool) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id, ouID, limit, offset, includeDisplay)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignments'
type RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call struct {
	*mock.Call
}

// GetRoleAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ouID string
//   - limit int
//   - offset int
//   - includeDisplay bool
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) GetRoleAssignments(ctx interface{}, id interface{}, ouID interface{}, limit interface{}, offset interface{}, includeDisplay interface{}) *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call {
	return &RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call{Call: _e.mock.On("GetRoleAssignments", ctx, id, ouID, limit, offset, includeDisplay)}
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call) Run(run func(ctx context.Context, id string, ouID string, limit int, offset int, includeDisplay bool)) *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call) Return(assignmentList *AssignmentList, serviceError *common.ServiceError) *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(assignmentList, serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, ouID string, limit int, offset int, includeDisplay bool) (*AssignmentList, *common.ServiceError)) *RoleAssignmentServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignmentsByType provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) GetRoleAssignmentsByType(ctx context.Context, id string, ouID string, limit int, offset int, includeDisplay bool, assigneeType string) (*AssignmentList, *common.ServiceError) {
	ret := _mock.Called(ctx, id, ouID, limit, offset, includeDisplay, assigneeType)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignmentsByType")
	}

	var r0 *AssignmentList
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int, bool, string) (*AssignmentList, *common.ServiceError)); ok {
		return returnFunc(ctx, id, ouID, limit, offset, includeDisplay, assigneeType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int, bool, string) *AssignmentList); ok {
		r0 = returnFunc(ctx, id, ouID, limit, offset, includeDisplay, assigneeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AssignmentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int, bool, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id, ouID, limit, offset, includeDisplay, assigneeType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignmentsByType'
type RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call struct {
	*mock.Call
}

// GetRoleAssignmentsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ouID string
//   - limit int
//   - offset int
//   - includeDisplay bool
//   - assigneeType string
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) GetRoleAssignmentsByType(ctx interface{}, id interface{}, ouID interface{}, limit interface{}, offset interface{}, includeDisplay interface{}, assigneeType interface{}) *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	return &RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call{Call: _e.mock.On("GetRoleAssignmentsByType", ctx, id, ouID, limit, offset, includeDisplay, assigneeType)}
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call) Run(run func(ctx context.Context, id string, ouID string, limit int, offset int, includeDisplay bool, assigneeType string)) *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call) Return(assignmentList *AssignmentList, serviceError *common.ServiceError) *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Return(assignmentList, serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call) RunAndReturn(run func(ctx context.Context, id string, ouID string, limit int, offset int, includeDisplay bool, assigneeType string) (*AssignmentList, *common.ServiceError)) *RoleAssignmentServiceInterfaceMock_GetRoleAssignmentsByType_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAssignments provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) RemoveAssignments(ctx context.Context, id string, ouID string, assignments []RoleAssignment) *common.ServiceError {
	ret := _mock.Called(ctx, id, ouID, assignments)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAssignments")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []RoleAssignment) *common.ServiceError); ok {
		r0 = returnFunc(ctx, id, ouID, assignments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAssignments'
type RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call struct {
	*mock.Call
}

// RemoveAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ouID string
//   - assignments []RoleAssignment
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) RemoveAssignments(ctx interface{}, id interface{}, ouID interface{}, assignments interface{}) *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call {
	return &RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call{Call: _e.mock.On("RemoveAssignments", ctx, id, ouID, assignments)}
}

func (_c *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call) Run(run func(ctx context.Context, id string, ouID string, assignments []RoleAssignment)) *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []RoleAssignment
		if args[3] != nil {
			arg3 = args[3].([]RoleAssignment)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call) Return(serviceError *common.ServiceError) *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call) RunAndReturn(run func(ctx context.Context, id string, ouID string, assignments []RoleAssignment) *common.ServiceError) *RoleAssignmentServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveAssignmentOUIDs provides a mock function for the type RoleAssignmentServiceInterfaceMock
func (_mock *RoleAssignmentServiceInterfaceMock) ResolveAssignmentOUIDs(ctx context.Context, assignments []RoleAssignment) ([]RoleAssignment, *common.ServiceError) {
	ret := _mock.Called(ctx, assignments)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAssignmentOUIDs")
	}

	var r0 []RoleAssignment
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, []RoleAssignment) ([]RoleAssignment, *common.ServiceError)); ok {
		return returnFunc(ctx, assignments)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []RoleAssignment) []RoleAssignment); ok {
		r0 = returnFunc(ctx, assignments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RoleAssignment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []RoleAssignment) *common.ServiceError); ok {
		r1 = returnFunc(ctx, assignments)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAssignmentOUIDs'
type RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call struct {
	*mock.Call
}

// ResolveAssignmentOUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - assignments []RoleAssignment
func (_e *RoleAssignmentServiceInterfaceMock_Expecter) ResolveAssignmentOUIDs(ctx interface{}, assignments interface{}) *RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call {
	return &RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call{Call: _e.mock.On("ResolveAssignmentOUIDs", ctx, assignments)}
}

func (_c *RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call) Run(run func(ctx context.Context, assignments []RoleAssignment)) *RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []RoleAssignment
		if args[1] != nil {
			arg1 = args[1].([]RoleAssignment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call) Return(roleAssignments []RoleAssignment, serviceError *common.ServiceError) *RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call {
	_c.Call.Return(roleAssignments, serviceError)
	return _c
}

func (_c *RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call) RunAndReturn(run func(ctx context.Context, assignments []RoleAssignment) ([]RoleAssignment, *common.ServiceError)) *RoleAssignmentServiceInterfaceMock_ResolveAssignmentOUIDs_Call {
	_c.Call.Return(run)
	return _c
}
