// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resourcemock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/resource"
	"github.com/thunder-id/thunderid/internal/sharing"
	"github.com/thunder-id/thunderid/internal/system/resourcedependency"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/providers"
)

// NewResourceServiceInterfaceMock creates a new instance of ResourceServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceServiceInterfaceMock {
	mock := &ResourceServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceServiceInterfaceMock is an autogenerated mock type for the ResourceServiceInterface type
type ResourceServiceInterfaceMock struct {
	mock.Mock
}

type ResourceServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceServiceInterfaceMock) EXPECT() *ResourceServiceInterfaceMock_Expecter {
	return &ResourceServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateAction provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) CreateAction(ctx context.Context, resourceServerID string, resourceID *string, action providers.Action) (*providers.Action, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, resourceID, action)

	if len(ret) == 0 {
		panic("no return value specified for CreateAction")
	}

	var r0 *providers.Action
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, providers.Action) (*providers.Action, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, resourceID, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, providers.Action) *providers.Action); ok {
		r0 = returnFunc(ctx, resourceServerID, resourceID, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, providers.Action) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, resourceID, action)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_CreateAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAction'
type ResourceServiceInterfaceMock_CreateAction_Call struct {
	*mock.Call
}

// CreateAction is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - resourceID *string
//   - action providers.Action
func (_e *ResourceServiceInterfaceMock_Expecter) CreateAction(ctx interface{}, resourceServerID interface{}, resourceID interface{}, action interface{}) *ResourceServiceInterfaceMock_CreateAction_Call {
	return &ResourceServiceInterfaceMock_CreateAction_Call{Call: _e.mock.On("CreateAction", ctx, resourceServerID, resourceID, action)}
}

func (_c *ResourceServiceInterfaceMock_CreateAction_Call) Run(run func(ctx context.Context, resourceServerID string, resourceID *string, action providers.Action)) *ResourceServiceInterfaceMock_CreateAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 providers.Action
		if args[3] != nil {
			arg3 = args[3].(providers.Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateAction_Call) Return(action1 *providers.Action, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_CreateAction_Call {
	_c.Call.Return(action1, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateAction_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, resourceID *string, action providers.Action) (*providers.Action, *common.ServiceError)) *ResourceServiceInterfaceMock_CreateAction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) CreateResource(ctx context.Context, resourceServerID string, res providers.Resource) (*providers.Resource, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, res)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 *providers.Resource
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, providers.Resource) (*providers.Resource, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, res)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, providers.Resource) *providers.Resource); ok {
		r0 = returnFunc(ctx, resourceServerID, res)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, providers.Resource) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, res)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type ResourceServiceInterfaceMock_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - res providers.Resource
func (_e *ResourceServiceInterfaceMock_Expecter) CreateResource(ctx interface{}, resourceServerID interface{}, res interface{}) *ResourceServiceInterfaceMock_CreateResource_Call {
	return &ResourceServiceInterfaceMock_CreateResource_Call{Call: _e.mock.On("CreateResource", ctx, resourceServerID, res)}
}

func (_c *ResourceServiceInterfaceMock_CreateResource_Call) Run(run func(ctx context.Context, resourceServerID string, res providers.Resource)) *ResourceServiceInterfaceMock_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 providers.Resource
		if args[2] != nil {
			arg2 = args[2].(providers.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateResource_Call) Return(resource *providers.Resource, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_CreateResource_Call {
	_c.Call.Return(resource, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateResource_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, res providers.Resource) (*providers.Resource, *common.ServiceError)) *ResourceServiceInterfaceMock_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) CreateResourceServer(ctx context.Context, rs providers.ResourceServer) (*providers.ResourceServer, *common.ServiceError) {
	ret := _mock.Called(ctx, rs)

	if len(ret) == 0 {
		panic("no return value specified for CreateResourceServer")
	}

	var r0 *providers.ResourceServer
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, providers.ResourceServer) (*providers.ResourceServer, *common.ServiceError)); ok {
		return returnFunc(ctx, rs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, providers.ResourceServer) *providers.ResourceServer); ok {
		r0 = returnFunc(ctx, rs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, providers.ResourceServer) *common.ServiceError); ok {
		r1 = returnFunc(ctx, rs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_CreateResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResourceServer'
type ResourceServiceInterfaceMock_CreateResourceServer_Call struct {
	*mock.Call
}

// CreateResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - rs providers.ResourceServer
func (_e *ResourceServiceInterfaceMock_Expecter) CreateResourceServer(ctx interface{}, rs interface{}) *ResourceServiceInterfaceMock_CreateResourceServer_Call {
	return &ResourceServiceInterfaceMock_CreateResourceServer_Call{Call: _e.mock.On("CreateResourceServer", ctx, rs)}
}

func (_c *ResourceServiceInterfaceMock_CreateResourceServer_Call) Run(run func(ctx context.Context, rs providers.ResourceServer)) *ResourceServiceInterfaceMock_CreateResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 providers.ResourceServer
		if args[1] != nil {
			arg1 = args[1].(providers.ResourceServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateResourceServer_Call) Return(resourceServer *providers.ResourceServer, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_CreateResourceServer_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateResourceServer_Call) RunAndReturn(run func(ctx context.Context, rs providers.ResourceServer) (*providers.ResourceServer, *common.ServiceError)) *ResourceServiceInterfaceMock_CreateResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAction provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) DeleteAction(ctx context.Context, resourceServerID string, resourceID *string, id string) *common.ServiceError {
	ret := _mock.Called(ctx, resourceServerID, resourceID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAction")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, resourceServerID, resourceID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_DeleteAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAction'
type ResourceServiceInterfaceMock_DeleteAction_Call struct {
	*mock.Call
}

// DeleteAction is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - resourceID *string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) DeleteAction(ctx interface{}, resourceServerID interface{}, resourceID interface{}, id interface{}) *ResourceServiceInterfaceMock_DeleteAction_Call {
	return &ResourceServiceInterfaceMock_DeleteAction_Call{Call: _e.mock.On("DeleteAction", ctx, resourceServerID, resourceID, id)}
}

func (_c *ResourceServiceInterfaceMock_DeleteAction_Call) Run(run func(ctx context.Context, resourceServerID string, resourceID *string, id string)) *ResourceServiceInterfaceMock_DeleteAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteAction_Call) Return(serviceError *common.ServiceError) *ResourceServiceInterfaceMock_DeleteAction_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteAction_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, resourceID *string, id string) *common.ServiceError) *ResourceServiceInterfaceMock_DeleteAction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) DeleteResource(ctx context.Context, resourceServerID string, id string) *common.ServiceError {
	ret := _mock.Called(ctx, resourceServerID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, resourceServerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type ResourceServiceInterfaceMock_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) DeleteResource(ctx interface{}, resourceServerID interface{}, id interface{}) *ResourceServiceInterfaceMock_DeleteResource_Call {
	return &ResourceServiceInterfaceMock_DeleteResource_Call{Call: _e.mock.On("DeleteResource", ctx, resourceServerID, id)}
}

func (_c *ResourceServiceInterfaceMock_DeleteResource_Call) Run(run func(ctx context.Context, resourceServerID string, id string)) *ResourceServiceInterfaceMock_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteResource_Call) Return(serviceError *common.ServiceError) *ResourceServiceInterfaceMock_DeleteResource_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteResource_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, id string) *common.ServiceError) *ResourceServiceInterfaceMock_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) DeleteResourceServer(ctx context.Context, id string) *common.ServiceError {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResourceServer")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_DeleteResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResourceServer'
type ResourceServiceInterfaceMock_DeleteResourceServer_Call struct {
	*mock.Call
}

// DeleteResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) DeleteResourceServer(ctx interface{}, id interface{}) *ResourceServiceInterfaceMock_DeleteResourceServer_Call {
	return &ResourceServiceInterfaceMock_DeleteResourceServer_Call{Call: _e.mock.On("DeleteResourceServer", ctx, id)}
}

func (_c *ResourceServiceInterfaceMock_DeleteResourceServer_Call) Run(run func(ctx context.Context, id string)) *ResourceServiceInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteResourceServer_Call) Return(serviceError *common.ServiceError) *ResourceServiceInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string) *common.ServiceError) *ResourceServiceInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// FilterVisiblePermissions provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) FilterVisiblePermissions(ctx context.Context, resourceServerID string, permissions []string, ouID string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, permissions, ouID)

	if len(ret) == 0 {
		panic("no return value specified for FilterVisiblePermissions")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, permissions, ouID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, string) []string); ok {
		r0 = returnFunc(ctx, resourceServerID, permissions, ouID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, permissions, ouID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_FilterVisiblePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterVisiblePermissions'
type ResourceServiceInterfaceMock_FilterVisiblePermissions_Call struct {
	*mock.Call
}

// FilterVisiblePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - permissions []string
//   - ouID string
func (_e *ResourceServiceInterfaceMock_Expecter) FilterVisiblePermissions(ctx interface{}, resourceServerID interface{}, permissions interface{}, ouID interface{}) *ResourceServiceInterfaceMock_FilterVisiblePermissions_Call {
	return &ResourceServiceInterfaceMock_FilterVisiblePermissions_Call{Call: _e.mock.On("FilterVisiblePermissions", ctx, resourceServerID, permissions, ouID)}
}

func (_c *ResourceServiceInterfaceMock_FilterVisiblePermissions_Call) Run(run func(ctx context.Context, resourceServerID string, permissions []string, ouID string)) *ResourceServiceInterfaceMock_FilterVisiblePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_FilterVisiblePermissions_Call) Return(strings []string, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_FilterVisiblePermissions_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_FilterVisiblePermissions_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, permissions []string, ouID string) ([]string, *common.ServiceError)) *ResourceServiceInterfaceMock_FilterVisiblePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetAction provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetAction(ctx context.Context, resourceServerID string, resourceID *string, id string) (*providers.Action, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, resourceID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAction")
	}

	var r0 *providers.Action
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string) (*providers.Action, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, resourceID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string) *providers.Action); ok {
		r0 = returnFunc(ctx, resourceServerID, resourceID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, resourceID, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAction'
type ResourceServiceInterfaceMock_GetAction_Call struct {
	*mock.Call
}

// GetAction is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - resourceID *string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) GetAction(ctx interface{}, resourceServerID interface{}, resourceID interface{}, id interface{}) *ResourceServiceInterfaceMock_GetAction_Call {
	return &ResourceServiceInterfaceMock_GetAction_Call{Call: _e.mock.On("GetAction", ctx, resourceServerID, resourceID, id)}
}

func (_c *ResourceServiceInterfaceMock_GetAction_Call) Run(run func(ctx context.Context, resourceServerID string, resourceID *string, id string)) *ResourceServiceInterfaceMock_GetAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetAction_Call) Return(action *providers.Action, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetAction_Call {
	_c.Call.Return(action, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetAction_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, resourceID *string, id string) (*providers.Action, *common.ServiceError)) *ResourceServiceInterfaceMock_GetAction_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionList provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetActionList(ctx context.Context, resourceServerID string, resourceID *string, kind providers.ActionKind, limit int, offset int) (*resource.ActionList, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, resourceID, kind, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetActionList")
	}

	var r0 *resource.ActionList
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, providers.ActionKind, int, int) (*resource.ActionList, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, resourceID, kind, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, providers.ActionKind, int, int) *resource.ActionList); ok {
		r0 = returnFunc(ctx, resourceServerID, resourceID, kind, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resource.ActionList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, providers.ActionKind, int, int) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, resourceID, kind, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetActionList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionList'
type ResourceServiceInterfaceMock_GetActionList_Call struct {
	*mock.Call
}

// GetActionList is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - resourceID *string
//   - kind providers.ActionKind
//   - limit int
//   - offset int
func (_e *ResourceServiceInterfaceMock_Expecter) GetActionList(ctx interface{}, resourceServerID interface{}, resourceID interface{}, kind interface{}, limit interface{}, offset interface{}) *ResourceServiceInterfaceMock_GetActionList_Call {
	return &ResourceServiceInterfaceMock_GetActionList_Call{Call: _e.mock.On("GetActionList", ctx, resourceServerID, resourceID, kind, limit, offset)}
}

func (_c *ResourceServiceInterfaceMock_GetActionList_Call) Run(run func(ctx context.Context, resourceServerID string, resourceID *string, kind providers.ActionKind, limit int, offset int)) *ResourceServiceInterfaceMock_GetActionList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 providers.ActionKind
		if args[3] != nil {
			arg3 = args[3].(providers.ActionKind)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionList_Call) Return(actionList *resource.ActionList, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetActionList_Call {
	_c.Call.Return(actionList, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionList_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, resourceID *string, kind providers.ActionKind, limit int, offset int) (*resource.ActionList, *common.ServiceError)) *ResourceServiceInterfaceMock_GetActionList_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllResourceList provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetAllResourceList(ctx context.Context, resourceServerID string) ([]providers.Resource, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllResourceList")
	}

	var r0 []providers.Resource
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]providers.Resource, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []providers.Resource); ok {
		r0 = returnFunc(ctx, resourceServerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]providers.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetAllResourceList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllResourceList'
type ResourceServiceInterfaceMock_GetAllResourceList_Call struct {
	*mock.Call
}

// GetAllResourceList is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
func (_e *ResourceServiceInterfaceMock_Expecter) GetAllResourceList(ctx interface{}, resourceServerID interface{}) *ResourceServiceInterfaceMock_GetAllResourceList_Call {
	return &ResourceServiceInterfaceMock_GetAllResourceList_Call{Call: _e.mock.On("GetAllResourceList", ctx, resourceServerID)}
}

func (_c *ResourceServiceInterfaceMock_GetAllResourceList_Call) Run(run func(ctx context.Context, resourceServerID string)) *ResourceServiceInterfaceMock_GetAllResourceList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetAllResourceList_Call) Return(resources []providers.Resource, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetAllResourceList_Call {
	_c.Call.Return(resources, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetAllResourceList_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string) ([]providers.Resource, *common.ServiceError)) *ResourceServiceInterfaceMock_GetAllResourceList_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResource(ctx context.Context, resourceServerID string, id string) (*providers.Resource, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 *providers.Resource
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*providers.Resource, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *providers.Resource); ok {
		r0 = returnFunc(ctx, resourceServerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type ResourceServiceInterfaceMock_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) GetResource(ctx interface{}, resourceServerID interface{}, id interface{}) *ResourceServiceInterfaceMock_GetResource_Call {
	return &ResourceServiceInterfaceMock_GetResource_Call{Call: _e.mock.On("GetResource", ctx, resourceServerID, id)}
}

func (_c *ResourceServiceInterfaceMock_GetResource_Call) Run(run func(ctx context.Context, resourceServerID string, id string)) *ResourceServiceInterfaceMock_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResource_Call) Return(resource1 *providers.Resource, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetResource_Call {
	_c.Call.Return(resource1, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResource_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, id string) (*providers.Resource, *common.ServiceError)) *ResourceServiceInterfaceMock_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceDependencies provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceDependencies(ctx context.Context, resourceType string, id string) ([]resourcedependency.ResourceDependency, error) {
	ret := _mock.Called(ctx, resourceType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceDependencies")
	}

	var r0 []resourcedependency.ResourceDependency
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]resourcedependency.ResourceDependency, error)); ok {
		return returnFunc(ctx, resourceType, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []resourcedependency.ResourceDependency); ok {
		r0 = returnFunc(ctx, resourceType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resourcedependency.ResourceDependency)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceType, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceDependencies'
type ResourceServiceInterfaceMock_GetResourceDependencies_Call struct {
	*mock.Call
}

// GetResourceDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceDependencies(ctx interface{}, resourceType interface{}, id interface{}) *ResourceServiceInterfaceMock_GetResourceDependencies_Call {
	return &ResourceServiceInterfaceMock_GetResourceDependencies_Call{Call: _e.mock.On("GetResourceDependencies", ctx, resourceType, id)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceDependencies_Call) Run(run func(ctx context.Context, resourceType string, id string)) *ResourceServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceDependencies_Call) Return(resourceDependencys []resourcedependency.ResourceDependency, err error) *ResourceServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Return(resourceDependencys, err)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceDependencies_Call) RunAndReturn(run func(ctx context.Context, resourceType string, id string) ([]resourcedependency.ResourceDependency, error)) *ResourceServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceList provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceList(ctx context.Context, resourceServerID string, parentID *string, limit int, offset int) (*resource.ResourceList, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, parentID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceList")
	}

	var r0 *resource.ResourceList
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, int, int) (*resource.ResourceList, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, parentID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, int, int) *resource.ResourceList); ok {
		r0 = returnFunc(ctx, resourceServerID, parentID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resource.ResourceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, int, int) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, parentID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceList'
type ResourceServiceInterfaceMock_GetResourceList_Call struct {
	*mock.Call
}

// GetResourceList is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - parentID *string
//   - limit int
//   - offset int
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceList(ctx interface{}, resourceServerID interface{}, parentID interface{}, limit interface{}, offset interface{}) *ResourceServiceInterfaceMock_GetResourceList_Call {
	return &ResourceServiceInterfaceMock_GetResourceList_Call{Call: _e.mock.On("GetResourceList", ctx, resourceServerID, parentID, limit, offset)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceList_Call) Run(run func(ctx context.Context, resourceServerID string, parentID *string, limit int, offset int)) *ResourceServiceInterfaceMock_GetResourceList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceList_Call) Return(resourceList *resource.ResourceList, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetResourceList_Call {
	_c.Call.Return(resourceList, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceList_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, parentID *string, limit int, offset int) (*resource.ResourceList, *common.ServiceError)) *ResourceServiceInterfaceMock_GetResourceList_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceServer(ctx context.Context, id string) (*providers.ResourceServer, *common.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServer")
	}

	var r0 *providers.ResourceServer
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.ResourceServer, *common.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.ResourceServer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServer'
type ResourceServiceInterfaceMock_GetResourceServer_Call struct {
	*mock.Call
}

// GetResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceServer(ctx interface{}, id interface{}) *ResourceServiceInterfaceMock_GetResourceServer_Call {
	return &ResourceServiceInterfaceMock_GetResourceServer_Call{Call: _e.mock.On("GetResourceServer", ctx, id)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceServer_Call) Run(run func(ctx context.Context, id string)) *ResourceServiceInterfaceMock_GetResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServer_Call) Return(resourceServer *providers.ResourceServer, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetResourceServer_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string) (*providers.ResourceServer, *common.ServiceError)) *ResourceServiceInterfaceMock_GetResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServerByIdentifier provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceServerByIdentifier(ctx context.Context, identifier string) (*providers.ResourceServer, *common.ServiceError) {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerByIdentifier")
	}

	var r0 *providers.ResourceServer
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.ResourceServer, *common.ServiceError)); ok {
		return returnFunc(ctx, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.ResourceServer); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, identifier)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerByIdentifier'
type ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call struct {
	*mock.Call
}

// GetResourceServerByIdentifier is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceServerByIdentifier(ctx interface{}, identifier interface{}) *ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call {
	return &ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call{Call: _e.mock.On("GetResourceServerByIdentifier", ctx, identifier)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call) Run(run func(ctx context.Context, identifier string)) *ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call) Return(resourceServer *providers.ResourceServer, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call) RunAndReturn(run func(ctx context.Context, identifier string) (*providers.ResourceServer, *common.ServiceError)) *ResourceServiceInterfaceMock_GetResourceServerByIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServerList provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceServerList(ctx context.Context, limit int, offset int) (*resource.ResourceServerList, *common.ServiceError) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerList")
	}

	var r0 *resource.ResourceServerList
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*resource.ResourceServerList, *common.ServiceError)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *resource.ResourceServerList); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resource.ResourceServerList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) *common.ServiceError); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceServerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerList'
type ResourceServiceInterfaceMock_GetResourceServerList_Call struct {
	*mock.Call
}

// GetResourceServerList is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceServerList(ctx interface{}, limit interface{}, offset interface{}) *ResourceServiceInterfaceMock_GetResourceServerList_Call {
	return &ResourceServiceInterfaceMock_GetResourceServerList_Call{Call: _e.mock.On("GetResourceServerList", ctx, limit, offset)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerList_Call) Run(run func(ctx context.Context, limit int, offset int)) *ResourceServiceInterfaceMock_GetResourceServerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerList_Call) Return(resourceServerList *resource.ResourceServerList, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetResourceServerList_Call {
	_c.Call.Return(resourceServerList, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerList_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) (*resource.ResourceServerList, *common.ServiceError)) *ResourceServiceInterfaceMock_GetResourceServerList_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServersForOU provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceServersForOU(ctx context.Context, ouID string, limit int, offset int) (*resource.ResourceServerList, *common.ServiceError) {
	ret := _mock.Called(ctx, ouID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServersForOU")
	}

	var r0 *resource.ResourceServerList
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (*resource.ResourceServerList, *common.ServiceError)); ok {
		return returnFunc(ctx, ouID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) *resource.ResourceServerList); ok {
		r0 = returnFunc(ctx, ouID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resource.ResourceServerList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) *common.ServiceError); ok {
		r1 = returnFunc(ctx, ouID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceServersForOU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServersForOU'
type ResourceServiceInterfaceMock_GetResourceServersForOU_Call struct {
	*mock.Call
}

// GetResourceServersForOU is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - limit int
//   - offset int
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceServersForOU(ctx interface{}, ouID interface{}, limit interface{}, offset interface{}) *ResourceServiceInterfaceMock_GetResourceServersForOU_Call {
	return &ResourceServiceInterfaceMock_GetResourceServersForOU_Call{Call: _e.mock.On("GetResourceServersForOU", ctx, ouID, limit, offset)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceServersForOU_Call) Run(run func(ctx context.Context, ouID string, limit int, offset int)) *ResourceServiceInterfaceMock_GetResourceServersForOU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServersForOU_Call) Return(resourceServerList *resource.ResourceServerList, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_GetResourceServersForOU_Call {
	_c.Call.Return(resourceServerList, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServersForOU_Call) RunAndReturn(run func(ctx context.Context, ouID string, limit int, offset int) (*resource.ResourceServerList, *common.ServiceError)) *ResourceServiceInterfaceMock_GetResourceServersForOU_Call {
	_c.Call.Return(run)
	return _c
}

// IsResourceServerDeclarative provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) IsResourceServerDeclarative(id string) bool {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for IsResourceServerDeclarative")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsResourceServerDeclarative'
type ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call struct {
	*mock.Call
}

// IsResourceServerDeclarative is a helper method to define mock.On call
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) IsResourceServerDeclarative(id interface{}) *ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call {
	return &ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call{Call: _e.mock.On("IsResourceServerDeclarative", id)}
}

func (_c *ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call) Run(run func(id string)) *ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call) Return(b bool) *ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call) RunAndReturn(run func(id string) bool) *ResourceServiceInterfaceMock_IsResourceServerDeclarative_Call {
	_c.Call.Return(run)
	return _c
}

// ListActionGrants provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) ListActionGrants(ctx context.Context, resourceServerID string, resourceID *string, id string) ([]resource.GrantInfo, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, resourceID, id)

	if len(ret) == 0 {
		panic("no return value specified for ListActionGrants")
	}

	var r0 []resource.GrantInfo
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string) ([]resource.GrantInfo, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, resourceID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string) []resource.GrantInfo); ok {
		r0 = returnFunc(ctx, resourceServerID, resourceID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resource.GrantInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, resourceID, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_ListActionGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActionGrants'
type ResourceServiceInterfaceMock_ListActionGrants_Call struct {
	*mock.Call
}

// ListActionGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - resourceID *string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) ListActionGrants(ctx interface{}, resourceServerID interface{}, resourceID interface{}, id interface{}) *ResourceServiceInterfaceMock_ListActionGrants_Call {
	return &ResourceServiceInterfaceMock_ListActionGrants_Call{Call: _e.mock.On("ListActionGrants", ctx, resourceServerID, resourceID, id)}
}

func (_c *ResourceServiceInterfaceMock_ListActionGrants_Call) Run(run func(ctx context.Context, resourceServerID string, resourceID *string, id string)) *ResourceServiceInterfaceMock_ListActionGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_ListActionGrants_Call) Return(grantInfos []resource.GrantInfo, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_ListActionGrants_Call {
	_c.Call.Return(grantInfos, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_ListActionGrants_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, resourceID *string, id string) ([]resource.GrantInfo, *common.ServiceError)) *ResourceServiceInterfaceMock_ListActionGrants_Call {
	_c.Call.Return(run)
	return _c
}

// ListResourceGrants provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) ListResourceGrants(ctx context.Context, resourceServerID string, id string) ([]resource.GrantInfo, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, id)

	if len(ret) == 0 {
		panic("no return value specified for ListResourceGrants")
	}

	var r0 []resource.GrantInfo
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]resource.GrantInfo, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []resource.GrantInfo); ok {
		r0 = returnFunc(ctx, resourceServerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resource.GrantInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_ListResourceGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResourceGrants'
type ResourceServiceInterfaceMock_ListResourceGrants_Call struct {
	*mock.Call
}

// ListResourceGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) ListResourceGrants(ctx interface{}, resourceServerID interface{}, id interface{}) *ResourceServiceInterfaceMock_ListResourceGrants_Call {
	return &ResourceServiceInterfaceMock_ListResourceGrants_Call{Call: _e.mock.On("ListResourceGrants", ctx, resourceServerID, id)}
}

func (_c *ResourceServiceInterfaceMock_ListResourceGrants_Call) Run(run func(ctx context.Context, resourceServerID string, id string)) *ResourceServiceInterfaceMock_ListResourceGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_ListResourceGrants_Call) Return(grantInfos []resource.GrantInfo, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_ListResourceGrants_Call {
	_c.Call.Return(grantInfos, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_ListResourceGrants_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, id string) ([]resource.GrantInfo, *common.ServiceError)) *ResourceServiceInterfaceMock_ListResourceGrants_Call {
	_c.Call.Return(run)
	return _c
}

// ListResourceServerGrants provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) ListResourceServerGrants(ctx context.Context, id string) ([]resource.GrantInfo, *common.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListResourceServerGrants")
	}

	var r0 []resource.GrantInfo
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]resource.GrantInfo, *common.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []resource.GrantInfo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resource.GrantInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_ListResourceServerGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResourceServerGrants'
type ResourceServiceInterfaceMock_ListResourceServerGrants_Call struct {
	*mock.Call
}

// ListResourceServerGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) ListResourceServerGrants(ctx interface{}, id interface{}) *ResourceServiceInterfaceMock_ListResourceServerGrants_Call {
	return &ResourceServiceInterfaceMock_ListResourceServerGrants_Call{Call: _e.mock.On("ListResourceServerGrants", ctx, id)}
}

func (_c *ResourceServiceInterfaceMock_ListResourceServerGrants_Call) Run(run func(ctx context.Context, id string)) *ResourceServiceInterfaceMock_ListResourceServerGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_ListResourceServerGrants_Call) Return(grantInfos []resource.GrantInfo, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_ListResourceServerGrants_Call {
	_c.Call.Return(grantInfos, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_ListResourceServerGrants_Call) RunAndReturn(run func(ctx context.Context, id string) ([]resource.GrantInfo, *common.ServiceError)) *ResourceServiceInterfaceMock_ListResourceServerGrants_Call {
	_c.Call.Return(run)
	return _c
}

// RequireVisibility provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) RequireVisibility(ctx context.Context, resourceType sharing.ResourceType, resourceID string, owningOUID string) *common.ServiceError {
	ret := _mock.Called(ctx, resourceType, resourceID, owningOUID)

	if len(ret) == 0 {
		panic("no return value specified for RequireVisibility")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, sharing.ResourceType, string, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, owningOUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_RequireVisibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireVisibility'
type ResourceServiceInterfaceMock_RequireVisibility_Call struct {
	*mock.Call
}

// RequireVisibility is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType sharing.ResourceType
//   - resourceID string
//   - owningOUID string
func (_e *ResourceServiceInterfaceMock_Expecter) RequireVisibility(ctx interface{}, resourceType interface{}, resourceID interface{}, owningOUID interface{}) *ResourceServiceInterfaceMock_RequireVisibility_Call {
	return &ResourceServiceInterfaceMock_RequireVisibility_Call{Call: _e.mock.On("RequireVisibility", ctx, resourceType, resourceID, owningOUID)}
}

func (_c *ResourceServiceInterfaceMock_RequireVisibility_Call) Run(run func(ctx context.Context, resourceType sharing.ResourceType, resourceID string, owningOUID string)) *ResourceServiceInterfaceMock_RequireVisibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sharing.ResourceType
		if args[1] != nil {
			arg1 = args[1].(sharing.ResourceType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_RequireVisibility_Call) Return(serviceError *common.ServiceError) *ResourceServiceInterfaceMock_RequireVisibility_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_RequireVisibility_Call) RunAndReturn(run func(ctx context.Context, resourceType sharing.ResourceType, resourceID string, owningOUID string) *common.ServiceError) *ResourceServiceInterfaceMock_RequireVisibility_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveResourceServerOUHandle provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) ResolveResourceServerOUHandle(ctx context.Context, rs *providers.ResourceServer) *common.ServiceError {
	ret := _mock.Called(ctx, rs)

	if len(ret) == 0 {
		panic("no return value specified for ResolveResourceServerOUHandle")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providers.ResourceServer) *common.ServiceError); ok {
		r0 = returnFunc(ctx, rs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveResourceServerOUHandle'
type ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call struct {
	*mock.Call
}

// ResolveResourceServerOUHandle is a helper method to define mock.On call
//   - ctx context.Context
//   - rs *providers.ResourceServer
func (_e *ResourceServiceInterfaceMock_Expecter) ResolveResourceServerOUHandle(ctx interface{}, rs interface{}) *ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call {
	return &ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call{Call: _e.mock.On("ResolveResourceServerOUHandle", ctx, rs)}
}

func (_c *ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call) Run(run func(ctx context.Context, rs *providers.ResourceServer)) *ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *providers.ResourceServer
		if args[1] != nil {
			arg1 = args[1].(*providers.ResourceServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call) Return(serviceError *common.ServiceError) *ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call) RunAndReturn(run func(ctx context.Context, rs *providers.ResourceServer) *common.ServiceError) *ResourceServiceInterfaceMock_ResolveResourceServerOUHandle_Call {
	_c.Call.Return(run)
	return _c
}

// SetDependencyRegistry provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) SetDependencyRegistry(r resourcedependency.Registry) {
	_mock.Called(r)
	return
}

// ResourceServiceInterfaceMock_SetDependencyRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDependencyRegistry'
type ResourceServiceInterfaceMock_SetDependencyRegistry_Call struct {
	*mock.Call
}

// SetDependencyRegistry is a helper method to define mock.On call
//   - r resourcedependency.Registry
func (_e *ResourceServiceInterfaceMock_Expecter) SetDependencyRegistry(r interface{}) *ResourceServiceInterfaceMock_SetDependencyRegistry_Call {
	return &ResourceServiceInterfaceMock_SetDependencyRegistry_Call{Call: _e.mock.On("SetDependencyRegistry", r)}
}

func (_c *ResourceServiceInterfaceMock_SetDependencyRegistry_Call) Run(run func(r resourcedependency.Registry)) *ResourceServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 resourcedependency.Registry
		if args[0] != nil {
			arg0 = args[0].(resourcedependency.Registry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_SetDependencyRegistry_Call) Return() *ResourceServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Call.Return()
	return _c
}

func (_c *ResourceServiceInterfaceMock_SetDependencyRegistry_Call) RunAndReturn(run func(r resourcedependency.Registry)) *ResourceServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Run(run)
	return _c
}

// SetRolePermissionRevoker provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) SetRolePermissionRevoker(r resource.RolePermissionRevoker) {
	_mock.Called(r)
	return
}

// ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRolePermissionRevoker'
type ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call struct {
	*mock.Call
}

// SetRolePermissionRevoker is a helper method to define mock.On call
//   - r resource.RolePermissionRevoker
func (_e *ResourceServiceInterfaceMock_Expecter) SetRolePermissionRevoker(r interface{}) *ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call {
	return &ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call{Call: _e.mock.On("SetRolePermissionRevoker", r)}
}

func (_c *ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call) Run(run func(r resource.RolePermissionRevoker)) *ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 resource.RolePermissionRevoker
		if args[0] != nil {
			arg0 = args[0].(resource.RolePermissionRevoker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call) Return() *ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call {
	_c.Call.Return()
	return _c
}

func (_c *ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call) RunAndReturn(run func(r resource.RolePermissionRevoker)) *ResourceServiceInterfaceMock_SetRolePermissionRevoker_Call {
	_c.Run(run)
	return _c
}

// ShareAction provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) ShareAction(ctx context.Context, resourceServerID string, resourceID *string, id string, req resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, resourceID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for ShareAction")
	}

	var r0 []resource.GrantInfo
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string, resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, resourceID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string, resource.ShareRequest) []resource.GrantInfo); ok {
		r0 = returnFunc(ctx, resourceServerID, resourceID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resource.GrantInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, string, resource.ShareRequest) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, resourceID, id, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_ShareAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareAction'
type ResourceServiceInterfaceMock_ShareAction_Call struct {
	*mock.Call
}

// ShareAction is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - resourceID *string
//   - id string
//   - req resource.ShareRequest
func (_e *ResourceServiceInterfaceMock_Expecter) ShareAction(ctx interface{}, resourceServerID interface{}, resourceID interface{}, id interface{}, req interface{}) *ResourceServiceInterfaceMock_ShareAction_Call {
	return &ResourceServiceInterfaceMock_ShareAction_Call{Call: _e.mock.On("ShareAction", ctx, resourceServerID, resourceID, id, req)}
}

func (_c *ResourceServiceInterfaceMock_ShareAction_Call) Run(run func(ctx context.Context, resourceServerID string, resourceID *string, id string, req resource.ShareRequest)) *ResourceServiceInterfaceMock_ShareAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 resource.ShareRequest
		if args[4] != nil {
			arg4 = args[4].(resource.ShareRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_ShareAction_Call) Return(grantInfos []resource.GrantInfo, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_ShareAction_Call {
	_c.Call.Return(grantInfos, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_ShareAction_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, resourceID *string, id string, req resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError)) *ResourceServiceInterfaceMock_ShareAction_Call {
	_c.Call.Return(run)
	return _c
}

// ShareResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) ShareResource(ctx context.Context, resourceServerID string, id string, req resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for ShareResource")
	}

	var r0 []resource.GrantInfo
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, resource.ShareRequest) []resource.GrantInfo); ok {
		r0 = returnFunc(ctx, resourceServerID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resource.GrantInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, resource.ShareRequest) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, id, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_ShareResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareResource'
type ResourceServiceInterfaceMock_ShareResource_Call struct {
	*mock.Call
}

// ShareResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - id string
//   - req resource.ShareRequest
func (_e *ResourceServiceInterfaceMock_Expecter) ShareResource(ctx interface{}, resourceServerID interface{}, id interface{}, req interface{}) *ResourceServiceInterfaceMock_ShareResource_Call {
	return &ResourceServiceInterfaceMock_ShareResource_Call{Call: _e.mock.On("ShareResource", ctx, resourceServerID, id, req)}
}

func (_c *ResourceServiceInterfaceMock_ShareResource_Call) Run(run func(ctx context.Context, resourceServerID string, id string, req resource.ShareRequest)) *ResourceServiceInterfaceMock_ShareResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 resource.ShareRequest
		if args[3] != nil {
			arg3 = args[3].(resource.ShareRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_ShareResource_Call) Return(grantInfos []resource.GrantInfo, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_ShareResource_Call {
	_c.Call.Return(grantInfos, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_ShareResource_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, id string, req resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError)) *ResourceServiceInterfaceMock_ShareResource_Call {
	_c.Call.Return(run)
	return _c
}

// ShareResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) ShareResourceServer(ctx context.Context, id string, req resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for ShareResourceServer")
	}

	var r0 []resource.GrantInfo
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, resource.ShareRequest) []resource.GrantInfo); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resource.GrantInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, resource.ShareRequest) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_ShareResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareResourceServer'
type ResourceServiceInterfaceMock_ShareResourceServer_Call struct {
	*mock.Call
}

// ShareResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req resource.ShareRequest
func (_e *ResourceServiceInterfaceMock_Expecter) ShareResourceServer(ctx interface{}, id interface{}, req interface{}) *ResourceServiceInterfaceMock_ShareResourceServer_Call {
	return &ResourceServiceInterfaceMock_ShareResourceServer_Call{Call: _e.mock.On("ShareResourceServer", ctx, id, req)}
}

func (_c *ResourceServiceInterfaceMock_ShareResourceServer_Call) Run(run func(ctx context.Context, id string, req resource.ShareRequest)) *ResourceServiceInterfaceMock_ShareResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 resource.ShareRequest
		if args[2] != nil {
			arg2 = args[2].(resource.ShareRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_ShareResourceServer_Call) Return(grantInfos []resource.GrantInfo, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_ShareResourceServer_Call {
	_c.Call.Return(grantInfos, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_ShareResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string, req resource.ShareRequest) ([]resource.GrantInfo, *common.ServiceError)) *ResourceServiceInterfaceMock_ShareResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// UnshareActionGrant provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UnshareActionGrant(ctx context.Context, resourceServerID string, resourceID *string, id string, grantID string) *common.ServiceError {
	ret := _mock.Called(ctx, resourceServerID, resourceID, id, grantID)

	if len(ret) == 0 {
		panic("no return value specified for UnshareActionGrant")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, resourceServerID, resourceID, id, grantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_UnshareActionGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnshareActionGrant'
type ResourceServiceInterfaceMock_UnshareActionGrant_Call struct {
	*mock.Call
}

// UnshareActionGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - resourceID *string
//   - id string
//   - grantID string
func (_e *ResourceServiceInterfaceMock_Expecter) UnshareActionGrant(ctx interface{}, resourceServerID interface{}, resourceID interface{}, id interface{}, grantID interface{}) *ResourceServiceInterfaceMock_UnshareActionGrant_Call {
	return &ResourceServiceInterfaceMock_UnshareActionGrant_Call{Call: _e.mock.On("UnshareActionGrant", ctx, resourceServerID, resourceID, id, grantID)}
}

func (_c *ResourceServiceInterfaceMock_UnshareActionGrant_Call) Run(run func(ctx context.Context, resourceServerID string, resourceID *string, id string, grantID string)) *ResourceServiceInterfaceMock_UnshareActionGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UnshareActionGrant_Call) Return(serviceError *common.ServiceError) *ResourceServiceInterfaceMock_UnshareActionGrant_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UnshareActionGrant_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, resourceID *string, id string, grantID string) *common.ServiceError) *ResourceServiceInterfaceMock_UnshareActionGrant_Call {
	_c.Call.Return(run)
	return _c
}

// UnshareResourceGrant provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UnshareResourceGrant(ctx context.Context, resourceServerID string, id string, grantID string) *common.ServiceError {
	ret := _mock.Called(ctx, resourceServerID, id, grantID)

	if len(ret) == 0 {
		panic("no return value specified for UnshareResourceGrant")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, resourceServerID, id, grantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_UnshareResourceGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnshareResourceGrant'
type ResourceServiceInterfaceMock_UnshareResourceGrant_Call struct {
	*mock.Call
}

// UnshareResourceGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - id string
//   - grantID string
func (_e *ResourceServiceInterfaceMock_Expecter) UnshareResourceGrant(ctx interface{}, resourceServerID interface{}, id interface{}, grantID interface{}) *ResourceServiceInterfaceMock_UnshareResourceGrant_Call {
	return &ResourceServiceInterfaceMock_UnshareResourceGrant_Call{Call: _e.mock.On("UnshareResourceGrant", ctx, resourceServerID, id, grantID)}
}

func (_c *ResourceServiceInterfaceMock_UnshareResourceGrant_Call) Run(run func(ctx context.Context, resourceServerID string, id string, grantID string)) *ResourceServiceInterfaceMock_UnshareResourceGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UnshareResourceGrant_Call) Return(serviceError *common.ServiceError) *ResourceServiceInterfaceMock_UnshareResourceGrant_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UnshareResourceGrant_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, id string, grantID string) *common.ServiceError) *ResourceServiceInterfaceMock_UnshareResourceGrant_Call {
	_c.Call.Return(run)
	return _c
}

// UnshareResourceServerGrant provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UnshareResourceServerGrant(ctx context.Context, id string, grantID string) *common.ServiceError {
	ret := _mock.Called(ctx, id, grantID)

	if len(ret) == 0 {
		panic("no return value specified for UnshareResourceServerGrant")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, id, grantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnshareResourceServerGrant'
type ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call struct {
	*mock.Call
}

// UnshareResourceServerGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - grantID string
func (_e *ResourceServiceInterfaceMock_Expecter) UnshareResourceServerGrant(ctx interface{}, id interface{}, grantID interface{}) *ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call {
	return &ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call{Call: _e.mock.On("UnshareResourceServerGrant", ctx, id, grantID)}
}

func (_c *ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call) Run(run func(ctx context.Context, id string, grantID string)) *ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call) Return(serviceError *common.ServiceError) *ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call) RunAndReturn(run func(ctx context.Context, id string, grantID string) *common.ServiceError) *ResourceServiceInterfaceMock_UnshareResourceServerGrant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAction provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UpdateAction(ctx context.Context, resourceServerID string, resourceID *string, id string, action providers.Action) (*providers.Action, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, resourceID, id, action)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAction")
	}

	var r0 *providers.Action
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string, providers.Action) (*providers.Action, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, resourceID, id, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, string, providers.Action) *providers.Action); ok {
		r0 = returnFunc(ctx, resourceServerID, resourceID, id, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, string, providers.Action) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, resourceID, id, action)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_UpdateAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAction'
type ResourceServiceInterfaceMock_UpdateAction_Call struct {
	*mock.Call
}

// UpdateAction is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - resourceID *string
//   - id string
//   - action providers.Action
func (_e *ResourceServiceInterfaceMock_Expecter) UpdateAction(ctx interface{}, resourceServerID interface{}, resourceID interface{}, id interface{}, action interface{}) *ResourceServiceInterfaceMock_UpdateAction_Call {
	return &ResourceServiceInterfaceMock_UpdateAction_Call{Call: _e.mock.On("UpdateAction", ctx, resourceServerID, resourceID, id, action)}
}

func (_c *ResourceServiceInterfaceMock_UpdateAction_Call) Run(run func(ctx context.Context, resourceServerID string, resourceID *string, id string, action providers.Action)) *ResourceServiceInterfaceMock_UpdateAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 providers.Action
		if args[4] != nil {
			arg4 = args[4].(providers.Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateAction_Call) Return(action1 *providers.Action, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_UpdateAction_Call {
	_c.Call.Return(action1, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateAction_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, resourceID *string, id string, action providers.Action) (*providers.Action, *common.ServiceError)) *ResourceServiceInterfaceMock_UpdateAction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UpdateResource(ctx context.Context, resourceServerID string, id string, res providers.Resource) (*providers.Resource, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, id, res)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 *providers.Resource
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, providers.Resource) (*providers.Resource, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, id, res)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, providers.Resource) *providers.Resource); ok {
		r0 = returnFunc(ctx, resourceServerID, id, res)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, providers.Resource) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, id, res)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type ResourceServiceInterfaceMock_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - id string
//   - res providers.Resource
func (_e *ResourceServiceInterfaceMock_Expecter) UpdateResource(ctx interface{}, resourceServerID interface{}, id interface{}, res interface{}) *ResourceServiceInterfaceMock_UpdateResource_Call {
	return &ResourceServiceInterfaceMock_UpdateResource_Call{Call: _e.mock.On("UpdateResource", ctx, resourceServerID, id, res)}
}

func (_c *ResourceServiceInterfaceMock_UpdateResource_Call) Run(run func(ctx context.Context, resourceServerID string, id string, res providers.Resource)) *ResourceServiceInterfaceMock_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 providers.Resource
		if args[3] != nil {
			arg3 = args[3].(providers.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateResource_Call) Return(resource1 *providers.Resource, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_UpdateResource_Call {
	_c.Call.Return(resource1, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateResource_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, id string, res providers.Resource) (*providers.Resource, *common.ServiceError)) *ResourceServiceInterfaceMock_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UpdateResourceServer(ctx context.Context, id string, rs providers.ResourceServer) (*providers.ResourceServer, *common.ServiceError) {
	ret := _mock.Called(ctx, id, rs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceServer")
	}

	var r0 *providers.ResourceServer
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, providers.ResourceServer) (*providers.ResourceServer, *common.ServiceError)); ok {
		return returnFunc(ctx, id, rs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, providers.ResourceServer) *providers.ResourceServer); ok {
		r0 = returnFunc(ctx, id, rs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, providers.ResourceServer) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id, rs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_UpdateResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceServer'
type ResourceServiceInterfaceMock_UpdateResourceServer_Call struct {
	*mock.Call
}

// UpdateResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - rs providers.ResourceServer
func (_e *ResourceServiceInterfaceMock_Expecter) UpdateResourceServer(ctx interface{}, id interface{}, rs interface{}) *ResourceServiceInterfaceMock_UpdateResourceServer_Call {
	return &ResourceServiceInterfaceMock_UpdateResourceServer_Call{Call: _e.mock.On("UpdateResourceServer", ctx, id, rs)}
}

func (_c *ResourceServiceInterfaceMock_UpdateResourceServer_Call) Run(run func(ctx context.Context, id string, rs providers.ResourceServer)) *ResourceServiceInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 providers.ResourceServer
		if args[2] != nil {
			arg2 = args[2].(providers.ResourceServer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateResourceServer_Call) Return(resourceServer *providers.ResourceServer, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string, rs providers.ResourceServer) (*providers.ResourceServer, *common.ServiceError)) *ResourceServiceInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePermissions provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) ValidatePermissions(ctx context.Context, resourceServerID string, permissions []string) ([]string, *common.ServiceError) {
	ret := _mock.Called(ctx, resourceServerID, permissions)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePermissions")
	}

	var r0 []string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, *common.ServiceError)); ok {
		return returnFunc(ctx, resourceServerID, permissions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = returnFunc(ctx, resourceServerID, permissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, resourceServerID, permissions)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_ValidatePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePermissions'
type ResourceServiceInterfaceMock_ValidatePermissions_Call struct {
	*mock.Call
}

// ValidatePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
//   - permissions []string
func (_e *ResourceServiceInterfaceMock_Expecter) ValidatePermissions(ctx interface{}, resourceServerID interface{}, permissions interface{}) *ResourceServiceInterfaceMock_ValidatePermissions_Call {
	return &ResourceServiceInterfaceMock_ValidatePermissions_Call{Call: _e.mock.On("ValidatePermissions", ctx, resourceServerID, permissions)}
}

func (_c *ResourceServiceInterfaceMock_ValidatePermissions_Call) Run(run func(ctx context.Context, resourceServerID string, permissions []string)) *ResourceServiceInterfaceMock_ValidatePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_ValidatePermissions_Call) Return(strings []string, serviceError *common.ServiceError) *ResourceServiceInterfaceMock_ValidatePermissions_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_ValidatePermissions_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string, permissions []string) ([]string, *common.ServiceError)) *ResourceServiceInterfaceMock_ValidatePermissions_Call {
	_c.Call.Return(run)
	return _c
}
