// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resourcemock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRolePermissionRevokerMock creates a new instance of RolePermissionRevokerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRolePermissionRevokerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RolePermissionRevokerMock {
	mock := &RolePermissionRevokerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RolePermissionRevokerMock is an autogenerated mock type for the RolePermissionRevoker type
type RolePermissionRevokerMock struct {
	mock.Mock
}

type RolePermissionRevokerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RolePermissionRevokerMock) EXPECT() *RolePermissionRevokerMock_Expecter {
	return &RolePermissionRevokerMock_Expecter{mock: &_m.Mock}
}

// RevokeRolePermissionForOU provides a mock function for the type RolePermissionRevokerMock
func (_mock *RolePermissionRevokerMock) RevokeRolePermissionForOU(ctx context.Context, ouID string, resourceServerID string, permission string) (int, error) {
	ret := _mock.Called(ctx, ouID, resourceServerID, permission)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRolePermissionForOU")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (int, error)); ok {
		return returnFunc(ctx, ouID, resourceServerID, permission)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) int); ok {
		r0 = returnFunc(ctx, ouID, resourceServerID, permission)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, ouID, resourceServerID, permission)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RolePermissionRevokerMock_RevokeRolePermissionForOU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRolePermissionForOU'
type RolePermissionRevokerMock_RevokeRolePermissionForOU_Call struct {
	*mock.Call
}

// RevokeRolePermissionForOU is a helper method to define mock.On call
//   - ctx context.Context
//   - ouID string
//   - resourceServerID string
//   - permission string
func (_e *RolePermissionRevokerMock_Expecter) RevokeRolePermissionForOU(ctx interface{}, ouID interface{}, resourceServerID interface{}, permission interface{}) *RolePermissionRevokerMock_RevokeRolePermissionForOU_Call {
	return &RolePermissionRevokerMock_RevokeRolePermissionForOU_Call{Call: _e.mock.On("RevokeRolePermissionForOU", ctx, ouID, resourceServerID, permission)}
}

func (_c *RolePermissionRevokerMock_RevokeRolePermissionForOU_Call) Run(run func(ctx context.Context, ouID string, resourceServerID string, permission string)) *RolePermissionRevokerMock_RevokeRolePermissionForOU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RolePermissionRevokerMock_RevokeRolePermissionForOU_Call) Return(n int, err error) *RolePermissionRevokerMock_RevokeRolePermissionForOU_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *RolePermissionRevokerMock_RevokeRolePermissionForOU_Call) RunAndReturn(run func(ctx context.Context, ouID string, resourceServerID string, permission string) (int, error)) *RolePermissionRevokerMock_RevokeRolePermissionForOU_Call {
	_c.Call.Return(run)
	return _c
}
